### ISSUE TITLE
WASM doesn't necessarily have bindings for all Rust math functions

### ISSUE THREAD

**Issue by ryanisaacg** [ryanisaacg/quicksilver#115]

**Comment by IntrepidPig** [comment]
Is this why I get the error `import object field 'cosf' is not a Function`?

**Comment by ryanisaacg** [comment]
Yes, that would be the issue. To be honest I'm surprised, because it's a standard library function. Currently my solution is to bind it manually in the JS, but I can't really go through the entire stdlib and bind every single function. Possibly it will be solved by a future rustc update?
