### ISSUE TITLE
stdweb integration

### ISSUE THREAD

**Issue by ryanisaacg** [ryanisaacg/quicksilver#220]
stdweb and wasm-bindgen seem like they would make the JS side of the web deployment much simpler and much more integrated into the Rust ecosystem.

**Comment by ryanisaacg** [comment]
Blocked waiting for the next release of stdweb, which will land gamepad support

**Comment by aep** [comment]
any idea whats missing from rustwasm/bindgen to use it instead of stdweb? the former seems to be the upcoming standard.

**Comment by ryanisaacg** [comment]
If you look at [this thread](https://github.com/rustwasm/team/issues/226), the consensus is that stdweb will migrate to using wasm-bindgen behind the scenes once wasm-bindgen is complete enough. For now, stdweb provides the most complete interface to JS (especially considering arbitrary JS can be embedded in stdweb.)

I would certainly merge a PR to shift over to wasm-bindgen if there was any compelling reason, though!

**Comment by aep** [comment]
mostly i'm already committed to bindgen, and there's currently no way to use quicksilver together with other stuff. for example by instantiating it with a gl context
