### ISSUE TITLE
Create a step-by-step tutorial

### ISSUE THREAD

**Issue by ryanisaacg** [ryanisaacg/quicksilver#221]
Currently the examples and API docs cover basic API usage, but actually understanding how to build an application with quicksilver is left up to the reader

**Comment by Xoronic** [comment]
Hi! I would like to contribute to this project. Can I be assigned to this issue? I think it is a great first issue, because I would also learn more about the API while writing the tutorial.

**Comment by ryanisaacg** [comment]
I'd love to assign you, and consider this assigned to you, but I can't do it through GitHub's UI. Apparently assigning issues to people who aren't listed as "contributors" is an [open issue](https://github.com/isaacs/github/issues/100). 

Feel free to fork and open a PR and get cracking! I would definitely encourage WIP PRs so that if there's any issues we can catch them early.

**Comment by Xoronic** [comment]
While looking at the documentation, I got a bit confused.

It is the struct `graphics::Draw`. Normally I like to reason about a struct like it is an object: I know what an `Image` is, what an `Animation` is, a `Font`, etcetera. 

But what is a `Draw`? I cannot really put my finger on it. 
The description in the documentation is: 

> A single drawable item, with a transform, a blend color, and a depth. 

Wouldn't naming it `Sprite` or Shape` make more sense then?

**Comment by ryanisaacg** [comment]
Yeah I see what you mean. I used to call that struct a `Sprite`, but at the time you couldn't clone or re-use it, so I changed the name (I expect to be able to store a `Sprite` with a game object frame-to-frame). Now you can change the position, transformation, etc. 

I can open a PR when I get the time to rename it, or you can if you'd like, just make sure the PR is to merge into the `development` branch instead of `master`.

**Comment by Xoronic** [comment]
Should I write the tutorial in markdown, html, ..? Or maybe we could write tutorials in a [mdBook](https://github.com/rust-lang-nursery/mdBook)?

**Comment by ryanisaacg** [comment]
mdBook seems to be the best format choice

**Comment by Xoronic** [comment]
Refer to this PR (Work In Progres) for the progress on the tutorial(s): https://github.com/ryanisaacg/quicksilver/pull/235

**Comment by Xoronic** [comment]
I see youre making a lot of progress! I'm just commenting so you know I did not abandon the project, I am still here. I am very busy at the moment and will be for another week. But, after that, I will have lots and lots of spare time :)

**Comment by Xoronic** [comment]
I see youre making a lot of progress! I'm just commenting so you know I did not abandon the project, I am still here. I am very busy at the moment and will be for another week. But, after that, I will have lots and lots of spare time :)

**Comment by ryanisaacg** [comment]
Feel free to take as much time as you need. The next release likely won't be for a while so there's definitely no rush to be closing issues.

**Comment by Xoronic** [comment]
I got sidetracked and won't be working on this issue for a while. If anyone is interested to work on this issue, feel free to do so!
