### ISSUE TITLE
Find a way to upgrade futures

### ISSUE THREAD

**Issue by ryanisaacg** [ryanisaacg/quicksilver#222]
The 0.2 version of futures requires more buy-in to the architecture of the futures library, which could be a problem for wasm. This may requires adding wasm-specific futures implementations.

**Comment by memoryruins** [comment]
Noticed many crates are waiting for 0.3 before upgrading; however, stdweb successfully added some [support of 0.2.0](https://github.com/koute/stdweb/pull/206), which may benefit #220.

**Comment by ryanisaacg** [comment]
Huh, if stdweb is supporting futures, it's possible that we can use their implementation to deal with WASM contexts. Thanks for the heads up, I'll definitely look into that once we have stdweb support merged.

**Comment by ryanisaacg** [comment]
Well, futures 0.2 has been yanked. It seems the best option is to just stick with futures 0.1.x until futures 0.3 is stabilized? Either way, there's no need to look into upgrading until there's something to upgrade to.

**Comment by memoryruins** [comment]
0.2 was moved to [futures-preview](https://crates.io/crates/futures-preview)

Agreed, it's sensible to wait for 0.3, especially while there's many moving parts. Looks like they're making a lot of progress toward making 0.3 work with async notation :)
