### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by memoryruins** [ryanisaacg/quicksilver#240]
There were a couple assumptions made with #239:
- create pull request on development branch
- run ``cargo test --all``

Adding to CHANGES.md slipped my mind. A CONTRIBUTING.md would make preferences of what to add and run before opening a pull request clear.

By the way, love the direction with Quicksilver :)

**Comment by ryanisaacg** [comment]
Good point, I've opened a PR. I'd like to see what you think, because you have first-hand experience writing a Quicksilver PR (also cc @Xoronic as another recent contributor)

**Comment by memoryruins** [comment]
It looks great! Nice to see the check on the wasm examples is easy.
