### ISSUE TITLE
Add a function to draw arcs in a convenient way

### ISSUE THREAD

**Issue by ryanisaacg** [ryanisaacg/quicksilver#242]
The function should take a starting angle, an ending angle, a radius, and a center. Additionally, drawing a circle should become a subset of drawing an arc.

**Comment by icefoxen** [comment]
Check out the `lyon` crate.

**Comment by ryanisaacg** [comment]
Thanks for the heads up, I've opened issue #247 for Lyon support

**Comment by ryanisaacg** [comment]
Having *finally* looked into implementing lyon support, this will definitely be possible with lyon so no need to keep the issue open.
