### ISSUE TITLE
Windows: Minimize window and open it again, no graphics are displayed

### ISSUE THREAD

**Issue by DoumanAsh** [ryanisaacg/quicksilver#249]
I tried to use simple example from your repo with simple figures.

It seems that on Windows when you minimize windows and open it again, you can see only black screen.
I've added logging to draw method and can see it is getting called.
But despite that there is nothing on screen any longer except for blackness

```rust
extern crate quicksilver;
#[macro_use]
extern crate log;

//Local deps
extern crate rt;

use quicksilver::{
    State, run, input,
    geom::{Circle, Rectangle, Transform},
    graphics::{Color, Draw, Window, WindowBuilder}
};

struct Game;

impl State for Game {
    fn new() -> Self { Game }

    fn draw(&mut self, window: &mut Window) {
        info!("Draw");
        window.clear(Color::black());
        window.draw(&Draw::rectangle(Rectangle::new(100, 100, 32, 32)).with_color(Color::red()));
        window.draw(&Draw::rectangle(Rectangle::new(400, 300, 32, 32)).with_color(Color::blue()).with_transform(Transform::rotate(45)).with_z(10));
        window.draw(&Draw::circle(Circle::new(400, 300, 100)).with_color(Color::green()));
        window.present();
    }
}

fn main() {
    rt::init();
    info!("Start");
    run::<Game>(WindowBuilder::new("Test Game", 800, 600));
}
```

**Comment by ryanisaacg** [comment]
Huh, I'll look into that when I get back to my Windows box. Just for now, can you post your Windows version and Rust compiler version?

**Comment by DoumanAsh** [comment]
Rust version is `rustc 1.26.2 (594fb253c 2018-06-01)`
And I use Windows 10 x64

I recall there was similar issue with conrod https://github.com/PistonDevelopers/conrod/issues/892

But in that case it was hanging completely, in this case it is jsut not rendering any graphics

**Comment by ryanisaacg** [comment]
Well, I have the same setup and I can repro the issue very easily. I'll start looking into it ASAP.

**Comment by ryanisaacg** [comment]
A quick trip back through the codebase reveals this has been an issue for basically ever.

**Comment by ryanisaacg** [comment]
Thanks to the master / development split the PR doesn't get closed automatically. That's actually pretty annoying.

Anyway I patched the issue, feel free to re-open if that doesn't fix your problem but it fixes it on my end.

**Comment by DoumanAsh** [comment]
Thank you, I'll switch to github dependency and shall check it out.
