### ISSUE TITLE
Mismatched types

### ISSUE THREAD

**Issue by Byter09** [ryanisaacg/quicksilver#265]
Running some checks and my GitLab CI (rustfmt, clippy, tarpaulin) throws several warnings, including here:
https://github.com/ryanisaacg/quicksilver/blob/9ddd7ecc617dec0cbb64124db661cbc2b6ecaafb/src/lib.rs#L119-L122

It complains with this message:
> mismatched types [E0308]
> expected `*mut u8`, found `*mut i8`
> Inspection info: The Rust type checker.

The fact, that this is in the `lib.rs` made me question whether this is a bug in my type checker or something not addressed here - thus, this issue.

**Comment by ryanisaacg** [comment]
That code is correct but also not in the development branch, so it's a non-issue. It won't be included in future releases.

Thanks for the heads up, though!

**Comment by Byter09** [comment]
I am developing in the development branch. So what exactly do you mean with 
> not in the development branch

?
Am I not seeing something that prevents this bit from being included?

**Comment by ryanisaacg** [comment]
Oh crap, my bad!
That is 100% dead code that slipped past me! 

I'll PR to delete it (deallocate and allocate cstring) when I get the chance, or you can if you'd like. They were for writing the JS bridge by hand but development uses cargo web and stdweb.

Sorry!

**Comment by Byter09** [comment]
Ah! Yeah I can include it in my next PR (which will have Triangle and correct Line (as a shape) support!)
I hope that's not against the contributing rules. I mean its code not related to the PR...

**Comment by ryanisaacg** [comment]
I'd prefer to have it in separate PRs, because the squashing and merging means each PR is only 1 commit in the history. I'd like to keep each commit as small as is reasonable.

**Comment by Byter09** [comment]
Alright. Will do multiple then. Gimme one hour or so. I'm still working out the minimal requirements for Triangles and Lines to be drawn.
There seriously needs to be a refactor at how to use window.draw(). Implementing new shapes is a pain... 😢

**Comment by Byter09** [comment]
Yeah this is gonna take a bit longer so if you do it, I dont have to.
I'm currently implementing all required methods to support `Shape` for `Line` and `Triangle` and its just soo much redundant code 😪 

Definitely gonna do something about that in the future! 😄

**Comment by ryanisaacg** [comment]
Actually removed the functions this time 😄
