### ISSUE TITLE
Retrieve the data from an Image as a buffer

### ISSUE THREAD

**Issue by kaikalii** [ryanisaacg/quicksilver#268]
Could there be some kind of image buffer struct that allows implementors of `Drawable` to draw to it? This would have two uses:
* Taking screenshots (with the option to save them to a file)
* Rendering multiple `Drawable`s to an image so that the image can be transformed as a single unit

I am currently working on an application that uses [rust-sfml](https://github.com/jeremyletang/rust-sfml) for graphics. I want to switch to quicksilver, but my application needs to be able to do both of the things above, and the lack of this feature is the one thing keeping me from switching. SFML has a class called [RenderTexture](https://docs.rs/sfml/0.14.0/sfml/graphics/struct.RenderTexture.html), which has exactly this functionality.

Ideally, it would support views in the same way that a window does.

I see no reason that this feature could not work on both desktop and web.

**Comment by ryanisaacg** [comment]
Currently there's half of what you want: [the Surface API](https://docs.rs/quicksilver/0.2.1/quicksilver/graphics/struct.Surface.html), which allows for arbitrary render-to-texture. Currently there's no way to save it to a file, but it's a possibility, I suppose.

**Comment by ryanisaacg** [comment]
Mostly I hadn't though of needing to extract the data; I assume OpenGL has some way to do this, so it should be fairly easy.

**Comment by kaikalii** [comment]
It looks like the `gl` function that would be needed is [`gl::GetTextureImage()`](https://docs.rs/gl/0.10.0/gl/fn.GetTextureImage.html) ([origininal OpenGL reference](https://www.khronos.org/registry/OpenGL-Refpages/gl4/)).  I'll see if I can get it working for desktop later. I'm not sure about web.

**Comment by kaikalii** [comment]
It seems that the actual implementation of this is beyond me. It would be cool if someone else could look into it.

**Comment by ryanisaacg** [comment]
This should be in the next release, v0.3.4.
