### ISSUE TITLE
Clean up Drawable and rendering API frontend

### ISSUE THREAD

**Issue by ryanisaacg** [ryanisaacg/quicksilver#276]
There are a few principle problems:

- It's difficult to add support for new shapes: the only way to do it is to find a way to construct iterators
- Drawing requires unnecessary ceremony:

```rust
window.draw(&Sprite::image(&some_image, Vector::new(15, 15)).with_transform(Transform::rotate(45)).with_color(Color::green());
```

This could be written much simpler with a few method overloads like `draw`, `draw_blend`, `draw_trans`, and `draw_ex`, looking something like:

```rust
window.draw_ex(&some_image, Vector::new(15, 15), Transform::rotate(45), Color::green());
```

This would require some large changes. Namely:

- Drawable would need to have Transform and Color be parameters, not stored in the struct itself.
- Applying a blend and transform to an entire batch of vertices should be simple.
- Sprite should be removed, or it must be reversed in usage (`sprite.draw(window)` rather than `window.draw(sprite)`)

**Comment by Byter09** [comment]
Thank you for this. I would like to add some optional goals for this issue:
- modify vertices before drawing them
- modify triangles before drawing them

This opens up ways to implement AA (#254), and makes it possible to refine what exactly a drawable should look like.
Examples:
- anti-aliasing
- the hello world of graphics programming: the RGB triangle
- modifying vertices without writing shaders

But looking great so far. I finally get what you wanted to do :D

**Comment by ryanisaacg** [comment]
Huh, I thought I added the RGB triangle to the example list, but I guess not. After the 2 PR's I planned for this evening, I'll add that.
