### ISSUE TITLE
checking ButtonState::Pressed in update() results in multiple presses

### ISSUE THREAD

**Issue by kevinw** [ryanisaacg/quicksilver#282]
How do I check when a key gets pressed?

I see in `run_impl` in `src/state.rs` that timer.tick may call your state's update() method more than once:

```rust
    while running {
        running = events.generate_events(&mut app.window, &mut app.event_buffer);
        app.process_events();
        timer.tick(||  { 
            app.update(); 
            Duration::from_millis(16) 
        });
        app.draw();
        app.window.clear_temporary_states();
    }
```

But that `clear_temporary_states` gets called after draw.  That means if I do something like this in my update() method:

```rust
        match keyboard[Key::L] {
            ButtonState::Pressed => {
                println!("do thing");
            }
            _ => ()
        }
```

..."do thing" gets printed more than once, depending on the timing. How to get what I want? Keyboard.clear_temporary_events() is not public....

**Comment by ryanisaacg** [comment]
In fact, that clear_temporary_states should be called after `app.update()` and not at the end of the frame. I'll fix this when I get the chance, or you can feel free to submit a PR to fix it.

**Comment by ryanisaacg** [comment]
Should be all fixed in the development branch.
