### ISSUE TITLE
Adding pullrequest and issue templates

### ISSUE THREAD

**Issue by Xoronic** [ryanisaacg/quicksilver#295]
I suggest adding templates for issues and pull requests.

[Creating issue templates](https://help.github.com/articles/creating-issue-templates-for-your-repository/)
[Creating pull request templates](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)

UPDATE:
- [x] Issues
    - [x]  Template for a question (how do I build this, why is this structure named this, or what does this error message mean, etc.)
    - [x] Template for bug reports
    - [x] Template for feature requests
- [ ] Pull Requests
    - Start with a summary
    - What documentation was updated
    - Check: 
        - `CHANGES.md` updated?
        - Submitting to the right branch?
        - Tested code if appropriate?
        - present-tense?
    - more?

**Comment by ryanisaacg** [comment]
Would you believe me if I said it was already on my todo list for tomorrow? 😄
