### ISSUE TITLE
New Sector object and a more efficient way to draw circles

### ISSUE THREAD

**Issue by Byter09** [ryanisaacg/quicksilver#297]
As we already said at the end of #290, a new issue is needed for this.

The goals mentioned were the following:
- [ ] new `Sector` object
- [ ] `Sector` object is self-optimized, by only drawing a sub-`Sector` of itself if possible
- [ ] `Circle` will now simply use a `Sector` with an angle of 360°
  - which results in the circle also self-optimizing
- [ ] if `Circle` covers the visible area, draw a triangle (with the original `z` and `color` attributes), that can fit the rectangle of the visible area inside of itself, centered right on the viewport center
- [ ] implement an efficient algorithm, that places exactly the right amount of vertices to draw a smooth arc, which will automatically be used by the `Circle`

I hope we can condense everything in just this issue and also use it to share ideas / algorithms to do this as efficient as possible.

Also, @Xoronic, while I'm already working on the basic `sector.rs` with everything currently set to `unimplemented!()`, I'm still looking for a very basic way to generate all the vertices which will be used in `draw()`. How's the following?

0. add the vertex of the origin
1. start at `angle = - sector.angle/2`
2. add a vertex at that position using
`x = sector.radius * cos(angle) | y = sector.radius * sin(angle)`
3. add the minimum step-angle (`2.5 / sector.radius`) to angle and repeat 2. until our angle is bigger than `sector.angle/2`

This should in theory allow for a smooth and mirrored sector, right?

**Comment by Xoronic** [comment]
> start at angle = - sector.angle/2

I don't really get that.. Could you clarify that a bit? Why would you start there?

**Comment by Byter09** [comment]
Well my plan at first was to start with the center of the arc and "pan out" to both sides. Turns out, that maybe the minimum amount of vertices needed is not always odd. If the amount is odd, there will never be a vertex right on the center of the arc.

**Comment by Byter09** [comment]
Okay so I got the basics running.. but two things:
- I'm simply starting to draw on the right, no idea whether that intuitive or not and
- I'm using `Vec` to collect all vertices and triangles and I'm sure thats bad but don't know how to fix it **(help me...)**

Here's the code for it:
```rust
impl Drawable for Sector {
    fn draw(&self, window: &mut Window, params: DrawAttributes) {
        // minimum amount of vertices so the arc is smooth
        let arc_vertices = (0.2 * PI * self.r).ceil() as u32;

        let trans = Transform::translate(self.o)
            * params.transform
            * Transform::translate(-self.o);

        let mut vertices = Vec::new();
        let mut triangles = Vec::new();

        // origin
        vertices.push(Vertex::new_untextured(trans * self.o, params.color));

        for i in 0..=arc_vertices {
            let angle = (i as f32 * (self.a / arc_vertices as f32));
            let x = self.o.x + self.r * angle.to_radians().cos();
            let y =  self.o.y + self.r * angle.to_radians().sin();
            vertices.push(Vertex::new_untextured(trans * Vector::new(x, y), params.color));
        }

        for i in 0..arc_vertices {
            triangles.push(GpuTriangle::new_untextured([0, i + 1, i + 2], params.z))
        }

        window.add_vertices(vertices.iter().cloned(), triangles.iter().cloned());
    }
}
```

My example
```rust
window.draw_color(
    &Sector::new(200, 450, 100, 270),
    Transform::IDENTITY,
    Color::YELLOW
);
```
looks like this:
![pacman](https://user-images.githubusercontent.com/16060697/42713322-5821f5f8-86ef-11e8-8712-0a188d5086df.png)

I did not yet work on all the `overlaps_*` methods, the area, tests and all the other usual stuff that objects have and its getting really late. I'll probably finish that tomorrow if there are no complains (which there will be because of the Vec usage) and then move on to implement `Sector` in `Circle`.

**Comment by Xoronic** [comment]
> &Sector::new(200, 450, 100, 270),

So what does each value mean?

**Comment by Byter09** [comment]
Oh right. Thats `(X, Y, Radius, Angle (in degrees))`

**Comment by Xoronic** [comment]
The unit circle is what I am used to, actually. So I would expect the empty quarter in the bottom right..

![untitled](https://user-images.githubusercontent.com/30958364/42714006-c464a5ec-86f1-11e8-888c-7c10069181cf.png)

But I'm not sure what is common in game engines..

**Comment by Byter09** [comment]
So thats anti-clockwise? I could change that. Thats just a preference... isnt it? I'm not sure whats typical in game engines to be honest.

**Comment by Xoronic** [comment]
I will check out how unity3d does it :P

**Comment by Xoronic** [comment]
A *start* and *end* angle might be a good idea...

**Comment by Xoronic** [comment]
Javascript:
```javascript
context.moveTo(cx,cy);
context.arc(cx,cy,radius,startangle,endangle);
context.lineTo(cx,cy);
context.stroke(); // or context.fill()
```

**Comment by Xoronic** [comment]
> A start and end angle was my idea too, but makes Transform::rotate() absolutely useless :D

Why would it?

**Comment by Byter09** [comment]
Right now, with only the angle given, it's 4 parameters and `rotate()` if you want to... well... rotate it. With start and end angle we have 5 and make `rotate()` useless, because if we have something like...
```
start = 180;
end = 360;
```
it is equivalent to
```
angle = 180;
Transform::rotate(180);
```

I guess this is... debatable? What do you think @ryanisaacg?

**Comment by Xoronic** [comment]
But we are already doing that, right?

For example for rectangles. You could create a bigger rectangle or scale it, it is equivalent.

**Comment by Xoronic** [comment]
Lyon's API looks well designed and the code looks clean. Think it's really worth considering

**Comment by Xoronic** [comment]
They are at version 0.11.0 right now though..

**Comment by Byter09** [comment]
I can't find sectors in lyon, so we would revert to giving it the vertices, which ends up being the same problem, right? Am I not understanding something here?

**Comment by ryanisaacg** [comment]
It seems to have arcs, which do seem to be equivalent to the sectors you've been describing. I'm not positive that they are, though.

**Comment by Xoronic** [comment]
Arcs would help drawing sectors with less code.

**Comment by Xoronic** [comment]
It provides an abstraction:

We give it paths, and it gives us the vertices and indices.

**Comment by Byter09** [comment]
So. How about testing lyon out with `Sector`s then? Two flies with one stone huh? We have two ways to do it: Either we path along our sector and give that to lyon or use the `Arc` they provide. I think we should go for the second option.

But: I'd prefer it, if someone else tests that, because I am really no expert at this. I'll just play around with it, and if I produce something useful, I'll let you know 😋

**Comment by ryanisaacg** [comment]
It seemed like this was closable if we could support lyon, is that the case?

**Comment by Byter09** [comment]
Well, there's still no `Sector` object and I have not tested lyons arc, so I can't say whether this is supported now.. Also, the overhauled circle is also not in yet, because I was quite busy the last week. Especially the self-optimization can give a huge boost in performance, if implemented correctly.

I'd leave this open in case @Xoronic or I can work this out. Let's just make this a 0.4 feature :P

**Comment by ryanisaacg** [comment]
I think I'm going to close this for inactivity for now, but feel free to revisit this if you want!
