### ISSUE TITLE
A few simple questions

### ISSUE THREAD

**Issue by Jokler** [ryanisaacg/quicksilver#306]
Is there currently any way to:
* Enable/Disable VSync
* Exit gracefully
* Accept text input instead of checking key states

**Comment by ryanisaacg** [comment]
Sorry to say: No, no, and no.

On the desktop vsync being on is a convenience feature, as it's often a sensible default; on the web, there's no way that I know of other than `requestAnimationFrame` or `setTimeout`/`setInterval` to do game loops, so vsync-like behavior is exhibited.

I hadn't thought about adding the ability to exit manually. I'd certainly add that as a feature, though deciding good behavior on the web might take some thought.

On text input, glutin doesn't really have great support for it (there's a `ReceivedCharacter` event but you still need to listen for keys such as backspace etc. yourself I believe) so I didn't add it. If there are things you would like to see (mapping key events to the character to make input collection easier?) let me know and I'll add them to the backlog.

**Comment by Jokler** [comment]
Is there any other problem with `ReceivedCharacter` since listening to backspace does not sound like it would create any real issues.
Simply mapping keys to characters would be problematic because the input should depend on the selected system keyboard.

**Comment by ryanisaacg** [comment]
I'd be amenable to adding support for text input using ReceivedCharacter (it might be a little more difficult on the web, but it should be doable.)

**Comment by Jokler** [comment]
That would be very useful.

I have another question.
Is there any way to switch to fullscreen or borderless windowed?

**Comment by ryanisaacg** [comment]
The `with_fullscreen` method on `WindowBuilder` can handle that before the game runs; support for doing it mid-run is planned for the next release ( see #230 )

**Comment by Jokler** [comment]
Ok, thanks. I did not check the issues on that, sorry. :)
