### ISSUE TITLE
variable draw and update rate

### ISSUE THREAD

**Issue by Byter09** [ryanisaacg/quicksilver#314]
Hi again.

So from what I read in some issues, the draw rate depends on v-sync, right? This is fine I guess.
But what about the update rate; why is it so low?
https://github.com/ryanisaacg/quicksilver/blob/d9d2ef00758d56bbe5922724dc9755f3a15356c8/src/state.rs#L133
This looks like the line giving the timer the tick rate. But why 16 ms? The end result from my calculations is, that `update` is called every 20 ms and `draw`  every 5 to 7 ms (on my 144hz monitor). (I used `Instant` and `.elapsed()` to get the time between calls.)

Now I know, that this is all pretty normal and should work for 90% of users, but I'm currently working on something, that requires a bit more than just 20ms. In fact, I would need `update` to be called as often as possible. (It's a physics problem which requires a really high physics-step, and I would _love_ to use quicksilver for this!)

---

I'm proposing a (hopefully) minor change, in that `update` and maybe even `draw` are called as often as possible. Additionally both should have an additional parameter giving the `Duration` that passed, since they were last called.

Positive effects of this are:
- the user can interpolate calculations more precise, as 20ms is just huge
- fps- and calculation-limiting methods can now be implemented by the user
- if quicksilver provides default limits, nothing changes on the API (except maybe 2 new methods to change the limits)

There are no negative effects that come to mind.

I hope this receives positive feedback and of course I'll help out wherever I can.

**Comment by Xoronic** [comment]
I think it is a great idea to *allow* API consumers to use a lower update rate, **but**:

> There are no negative effects that come to mind.

Wouldn't this change result in  a higher power consumption due to a higher load on the processor? (I'm not sure if it does)

**If it does draw more power**, it may be a good idea to let users choose the update frequency, but leave the default at 20ms or maybe 10ms.

> Now I know, that this is all pretty normal and should work for ***90% of users***, but I'm currently working on something, that requires a bit more than just 20ms. In fact, I would need update to be called as often as possible. (It's a physics problem which requires a really high physics-step, and I would love to use quicksilver for this!)

90% of the users. That is what (IMHO) a library should be built for. The 10% should be able to still achieve what they want, but the default should not favour the 10%, right?

**Comment by Byter09** [comment]
That's exactly my point. Default limits should still be there but one has to have a way to lower/raise them. See point 3 of my small list of positive effects :P

So basically, you agree. I guess... :D

**Comment by Xoronic** [comment]
> Additionally both should have an additional parameter giving the Duration that passed, since they were last called.

That is a great idea, and really necessary for physics. +1!

**Comment by ryanisaacg** [comment]
16 ms is a vague approximation for 60 frames-per-second, which seemed a reasonable default to me. It would be trivial (we're talking single-digit lines for the diff) to make this user-settable.

Delta time might be harder, especially on web, but I think that could be super valuable to do.

**Comment by Byter09** [comment]
First of, I wish there was a way to chat directly instead of using issue comments.
And secondly: We started working on a physics project and are not quite sure how to fix the wasm aspect but would love to use the development version of quicksilver. Is there any way to priotize this or help out?

**Comment by ryanisaacg** [comment]
@Byter09 We could set up a gitter chat, I think it's free and relatively simple.

**Comment by Byter09** [comment]
Oh wow great! I heard of Gitter before but never used it. Integrating my project was so easy. Already found you, too! Tell me when you created a room for Quicksilver 😄
