### ISSUE TITLE
Include assets in compiled binary

### ISSUE THREAD

**Issue by RyanCirincione** [ryanisaacg/quicksilver#330]
It would be nice to give quicksilver some sort of flag to have assets as part of the compiled binary.

- [x] Images
- [x] Fonts
- [ ] Sounds

**Comment by beatgammit** [comment]
Related: #331

**Comment by ryanisaacg** [comment]
This is blocked on loading sounds from binaries, see #219

**Comment by PonasKovas** [comment]
There are some crates specifically for this:
 - [icdir](https://crates.io/crates/incdir)
 - [embeddir](https://crates.io/crates/embeddir)

**Comment by ryanisaacg** [comment]
Because Quicksilver temporarily has no sound support, this issue can be closed. When sound support returns, it will be includable.
