### ISSUE TITLE
Unlocked update / draw rate

### ISSUE THREAD

**Issue by ryanisaacg** [ryanisaacg/quicksilver#337]
**Is your feature request related to a problem? Please describe.**
If users want the option of a truly and totally unlocked framerate, they should be able to have it.

**Describe the solution you'd like**
Give the users the ability to unlock their updates both in the WindowBuilder and in the running application (a Menu should probably be locked, even if it's attached to an application that would prefer to be unlocked.) This would require that users be able to query the time since the last update, which will only be a useful value for users running unlocked.

Additionally, there is the issue of vsync. Vsync will likely remain the only option on web, unless there is some way to configure `requestAnimationFrame` to update more often. However, a thread yield and no vsync should be a `WindowBuilder` or `Window` option on desktop.

**Comment by beatgammit** [comment]
You can always do `setTimeout(fn, 0)`, which should be faster than `requestAnimationFrame` (I think most implementations default to ~4ms or something).

However, I was having lockups already with the default and needed up reduce the draw rate to get things to work nicely.
