### ISSUE TITLE
Have images draw from the top-left corner instead of the middle

### ISSUE THREAD

**Issue by beatgammit** [ryanisaacg/quicksilver#339]
**Is your feature request related to a problem? Please describe.**

Drawing images is annoying since it draws from the middle of the image instead of the corner.

**Describe the solution you'd like**
Drawing images should either draw from the top-left corner (like many other libraries) or be able to pass in a Rectangle to `Draw::image` (or a similar function).

**Describe alternatives you've considered**
Improving the documentation would also have resolved my confusion, and would be needed anyway if this change is made.

**Are you interested in contributing?**
Sure! I mostly want direction as to which is preferred.

**Additional context**
I'm making a map editor for a tile-based game, so I may not speak for all users of this library.

**Comment by Byter09** [comment]
Are you using the development branch? Because there we have a textured rectangle, that takes an `Image` as a background.

**Comment by beatgammit** [comment]
No, I'm using 0.2.1. If it's already available it the development branch, I'll have to give it a try!

I'm finding that there's a bunch of other stuff I'll probably need that don't exist yet, so I'll check the dev branch before making new issues.

**Comment by beatgammit** [comment]
Ok, cool. It looks like none of the examples work (I tried two) on the latest development HEAD, and it's not wasm compatible. I'll stick with 0.2.1 for now, but I'll definitely get on gitter :)

**Comment by ryanisaacg** [comment]
I think I'll close this, because the actual issue title and body will be resolved in the 0.3.0 update.

**Comment by beatgammit** [comment]
Agreed. I played with the development branch, and I was able to get it to work.
