### ISSUE TITLE
No docs for development branch

### ISSUE THREAD

**Issue by beatgammit** [ryanisaacg/quicksilver#344]
**Describe the bug**
No docs for development branch

**To Reproduce**
1. Go to https://docs.rs/quicksilver
2. Click on the version picker at the top left
3. See no option for anything newer than 0.2.1

**Expected behavior**
Development docs are generated and available on docs.rs.

**Comment by ryanisaacg** [comment]
Unfortunately docs.rs only serves docs generated by crate versions available on crates.io

You can build the docs yourself locally with `cargo doc`, and we could also look into using Travis to generate development docs and host them on Github.

**Comment by beatgammit** [comment]
This was a relatively minor inconvenience, but I think it would be nice to have them hosted on Github since it would lower the barrier to entry. Then again, users would be using the latest stable, so this likely won't be a problem going forward.

**Comment by ryanisaacg** [comment]
Closing as a sub-issue of #378
