### ISSUE TITLE
Support canvas touch input events

### ISSUE THREAD

**Issue by soundrez** [ryanisaacg/quicksilver#366]
**Describe the problem you want to solve**

Touchscreen tap events are recorded as mouse click events. All other gestures are ignored.

**Describe the solution you'd like**

Map canvas touch events (long press, drag) to quicksilver mouse input events. Perhaps later on, a separate input type can be added.

**Are you interested in contributing?**

Yes, if this is a good first issue.

**Comment by ryanisaacg** [comment]
This would definitely be a good addition to `Event` (it would also be important if Quicksilver was to ever support mobile, even though that's not currently on the roadmap.)

I'm pretty sure the web touch APIs make this pretty doable, but I'm less sure how well-supported touch events are in glutin, the desktop windowing library. I would be okay with some features that are web-only if they were clearly documented that way, but I generally prefer to only add things that are cross-platform.

**Comment by ryanisaacg** [comment]
Oh, I misread your issue then. Yeah, if multitouch isn't a consideration, then this should be at least a little easier.

**Comment by rickyhan** [comment]
I added support for web touch api: https://github.com/koute/stdweb/pull/305

For quicksilver, a simple way to support touch is to forgo multitouch and simply convert the primary touch into a mouse event.

**Comment by ryanisaacg** [comment]
@soundrez This should be fixed on the development branch, and in the next release (0.3.5). Feel free to reopen if there are any problems.
