### ISSUE TITLE
Rework the animation system

### ISSUE THREAD

**Issue by ryanisaacg** [ryanisaacg/quicksilver#370]
**Describe the problem you want to solve**
Having many copies of an animation requires lots of copying of reference-counted pointers, and manually adjusting an animation is impossible.

**Describe the solution you'd like**
The animation system might not even need to exist: it's barely a good abstraction over an array and doing the modulo yourself, but if it should exist, there should be a higher-level and more efficient version of it.

**Comment by rickyhan** [comment]
IMO it's a useful abstraction where you can draw() as if it's an image and call play() to show it once.

This is my sprite animation impl:

https://github.com/rickyhan/dyn-grammar/blob/master/src/animation.rs

**Comment by ryanisaacg** [comment]
Because animations can be written by a user with no access to Quicksilver internals, I think this isn't a high priority anymore. It's unlikely that a single Animation abstraction will satisfy the needs of every Quicksilver user, so making the existing implementation more complicated doesn't seem important.
