### ISSUE TITLE
camera and  draw-geometry examples are the same on example.html

### ISSUE THREAD

**Issue by rofrol** [ryanisaacg/quicksilver#387]
**Describe the bug**

**To Reproduce**

**Environment and versions (please complete the following information):**
- Environment: 
- Rust compiler version: 
- Quicksilver verison:

**Comment by ryanisaacg** [comment]
They're not quite the same, actually: you can use the arrow keys to move the camera around!

But the fact that it isn't obvious on the example page is definitely a problem.
