### ISSUE TITLE
Transform PartialEq implementation incorrect

### ISSUE THREAD

**Issue by racharron** [ryanisaacg/quicksilver#399]
**Describe the bug**
Comparing if one transform is equal to another will return whether they are not equal.  

**To Reproduce**
```rust
use quicksilver::geom::Transform;
//  Will panic.
assert_eq!(Transform::IDENTITY, Transform::IDENTITY);
```

**Environment and versions (please complete the following information):**
- Environment: Windows 10
- Rust compiler version: Rust 1.29.2
- Quicksilver version: 0.3.1

**Comment by ryanisaacg** [comment]
Thanks for the report! It's been fixed in the development branch and will be fixed in the next release.
