### ISSUE TITLE
Rendering artifacts produced when rendering a font countdown

### ISSUE THREAD

**Issue by ryanisaacg** [ryanisaacg/quicksilver#405]
**Describe the bug**

See gitter chat and https://gist.github.com/drager/f7175bdaf5cbca5eadfbb380fe472bc2

**Comment by ryanisaacg** [comment]
@drager I'm still unable to reproduce this, do you have a more complete reproduction (e.g. a context for the snippet?)

**Comment by yuvallanger** [comment]
I have a weird font rendering artifact in the wasm32 version of the following project under the branch:

https://gitlab.com/yuvallanger/rectangly-rect/tree/weird_wasm_font_rendering_artefact
(for redundancy: https://gitlab.com/yuvallanger/rectangly-rect/tree/weird_wasm_font_rendering_artefact)

The latest hash is 54a0b700467c3be17d4b325cddfa869d12949882.

Run with `cargo web start`.
It might or might not be the same bug.

**Comment by ryanisaacg** [comment]
Thanks for the repro and screenshot! I'll look into it and update you with my progress.

**Comment by ryanisaacg** [comment]
@yuvallanger What's your OS / browser? On both Chrome and Firefox on mac, I get:

![image](https://user-images.githubusercontent.com/7978904/50615887-4e2d3b00-0eb4-11e9-9292-e2203b5664c4.png)

with no artifacting.

**Comment by yuvallanger** [comment]
I have tested it both on Chromium and Firefox.

## Chromium

```
$ chromium-browser --version
Chromium 71.0.3578.80 Built on Ubuntu , running on Ubuntu 18.04
```

## Firefox

```
$ firefox --version
Mozilla Firefox 64.0
```

## Ubuntu

```
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

**Comment by ryanisaacg** [comment]
Thanks! I'll try breaking out a Linux VM to see if I can repro there.

**Comment by drager** [comment]
@ryanisaacg Sorry for my late response. I haven't been able to reproduce my issue on the computer I'm at atm. Unfortunately I don't have access to that computer right now so hard to test on that now as well. Maybe it could have been missing/bad graphic drivers that caused the issue on that computer?

**Comment by jneumann** [comment]
I just tried this in Firefox on Mac OS and the same thing is happening to me on the website. Strangely it's not happening when I just run it as an application.

While messing around with it I found something very strange. I change the top string to "current score" and it showed this...
<img width="379" alt="screen shot 2019-03-01 at 2 17 19 pm" src="https://user-images.githubusercontent.com/4145595/53663978-d158dc00-3c2c-11e9-8de1-1aadb2a7105d.png">

**Comment by ryanisaacg** [comment]
Did updating Quicksilver solve it?

I still have never been able to reproduce this so I'm unsure where the bug even comes from.

**Comment by jneumann** [comment]
Updating the library worked to fix it on Mac OS, I can't say on Linux though I haven't had a chance to spin up a VM.

**Comment by ryanisaacg** [comment]
@yuvallanger Does updating solve your problem as well?

**Comment by ryanisaacg** [comment]
It seems this is fixed on newer versions. If anyone can reproduce this on 0.3.11, I will re-open.
