### ISSUE TITLE
Customize Asset Path for Web

### ISSUE THREAD

**Issue by rickyhan** [ryanisaacg/quicksilver#410]
Currently, the static assets must be under the same directory as the wasm file. When the .js file is loaded from a different URL other than generated index.html, static assets won't load.

**Comment by ryanisaacg** [comment]
I think this is blocked by: https://github.com/koute/cargo-web/issues/112

**Comment by rickyhan** [comment]
I made a pull request there: https://github.com/koute/cargo-web/pull/158

Does quicksilver parse Web.toml? How does this stdweb option propagate?

**Comment by ryanisaacg** [comment]
Quicksilver entirely defers to Web.toml for asset loading on the web, and just uses "static/" on desktop. To add support for asset loading from a non "static/" path within Quicksilver, it would probably involve parsing Web.toml

**Comment by rickyhan** [comment]
I actually prefer using static folder path as long as the mount path can be customized. Basically when you deploy, every Asset is prepended with the mount path which is specified in Web.toml.

**Comment by ryanisaacg** [comment]
I'm going to close this for now, let me know if you would like to re-open.
