### ISSUE TITLE
Camera example doesn't catch arrow key input

### ISSUE THREAD

**Issue by noomly** [ryanisaacg/quicksilver#425]
The example on https://www.ryanisaacg.com/quicksilver/example.html?camera should react on arrow keys input. It doesn't, even when compiled and ran locally.

Tested on the website, and locally under ArchLinux and rust nightly 1.33.0 with quicksilver 0.3.3.

When I try to replace `if window.keyboard()[Key::Up].is_down()` with `if window.keyboard()[Key::A].is_down()`, the camera does translate when I press `a`.

**Comment by ryanisaacg** [comment]
I'll look into it and will hopefully have a fix before the end of the weekend.

**Comment by ryanisaacg** [comment]
The fix is merged, it will be in version 0.3.4 which should be released soon. Let me know if the issue still remains after the fix!

**Comment by noomly** [comment]
Thanks for your work, you're doing an amazing job :)

I'll let you know.
