### ISSUE TITLE
Tilemap::region() yields unexpected results

### ISSUE THREAD

**Issue by Lokkij** [ryanisaacg/quicksilver#433]
Calling `Tilemap::region()` gives me a rectangle describing the tilemap region in terms of the number of tiles, whereas I would expect it to give me the region in terms of pixels. For example, calling `region` on a 10x10 tilemap with 50x50 tiles gives me a 10x10 rectangle where I would expect a 500x500 rectangle.

Looking at the source, it uses `Rectangle::new_sized(self.map_size)` where I would expect `Rectangle::new_sized(self.map_size * self.tile_size)`. I'm not sure whether this is intended behaviour with unclear documentation or an actual bug.

**Comment by ryanisaacg** [comment]
I would say this is a documentation error (and a fairly bad one at that, sorry!) I'll update the docs to reflect that the region is given in tiles.

**Comment by ryanisaacg** [comment]
Oh, I read your comment wrong. The expected behavior is that it would return a 500 x 500 Rectangle (as in, the argument to map_size in the constructor should be the size of the rectangle.) I thought you received this and had expected a different value. Can you post how you initialized the tilemap producing the incorrect results?

**Comment by Lokkij** [comment]
Aha! The confusion is in the constructor: I thought `map_size` was specified in tiles, not in pixels. Though it could be clearer, that does honestly make sense: almost everything about the Tilemap is in pixels, after all. It was my own expectations that caused the confusion.

For reference, here's the runnable example I was working from:
```rust
use quicksilver::geom::{Rectangle, Tilemap, Vector};
use quicksilver::graphics::{Background, Color};
use quicksilver::lifecycle::{State, Window};

struct Game {
    map: Tilemap<()>,
}

impl State for Game {
    fn new() -> quicksilver::Result<Self> {
        Ok(Game {
            map: Tilemap::new((10, 10), (50, 50)),
        })
    }

    fn draw(&mut self, window: &mut Window) -> quicksilver::Result<()> {
        window.clear(Color::YELLOW);
        let region = self.map.region();
        println!("The region: {:?}", region);
        window.draw(&region, Background::Col(Color::RED));
        Ok(())
    }
}

fn main() {
    quicksilver::lifecycle::run::<Game>(
        "Region example",
        Vector::new(800, 600),
        Default::default(),
    );
}
```

**Comment by ryanisaacg** [comment]
Ah, I would say that there should probably be a clarification in Tilemap::new but that seems to be more of a minor thing.
