### ISSUE TITLE
Need Unicode received Event

### ISSUE THREAD

**Issue by Riey** [ryanisaacg/quicksilver#435]
**Describe the problem you want to solve**

I want to handling unicode keyboard input

But KeyboardInput event is only way to handling keyboard input and it's just give me a Key enum

**Describe the solution you'd like**

There is a ReceivedCharacter event in winit's WindowEvent type

I think it's enough to just resend this event

**Are you interested in contributing?**

yes

I make a simple patch in my fork

https://github.com/Riey/quicksilver/tree/recv-char-event

**Comment by ryanisaacg** [comment]
Looks great! If you want to add wasm support feel free, otherwise some time this week I'll add wasm support and get this feature into the next release.

**Comment by Riey** [comment]
It seems to be little hard to apply on wasm

Because I can't find a method that change IME in canvas element

So maybe need a hidden input element

**Comment by ryanisaacg** [comment]
Let me know if #440 works for you! It should work on both desktop and web.

**Comment by ryanisaacg** [comment]
Software keyboard support isn't high on my radar, but if you want to contribute support for it with hidden elements be my guest!
