### ISSUE TITLE
WebGL artifacts on wasm32-unknown-unknown

### ISSUE THREAD

**Issue by rickyhan** [ryanisaacg/quicksilver#445]
**Describe the bug**
artifact when rendering image
![](https://i.imgur.com/6XWooR5.png)

**To Reproduce**

clone https://github.com/rickyhan/quicksilver-bug-repro

cargo web start

**Environment and versions (please complete the following information):**
- Environment: Ubuntu 18.04 LTS, chrome
- Rust compiler version: rustc 1.32.0-nightly (3e90a12a8 2018-11-29)
- Quicksilver verison: 0.3.4

**Comment by ryanisaacg** [comment]
I will get right on that, and it should hopefully be fixed within the next few days. Once it is fixed, a release will go out pretty much immediately!

**Comment by ryanisaacg** [comment]
Ah, it looks like this is already fixed on development! The next release will fix this issue for you.

**Comment by rickyhan** [comment]
Great! Thanks!
