### ISSUE TITLE
Let the run function accept a State object instead of forcing State::new() with no arguments

### ISSUE THREAD

**Issue by Kurble** [ryanisaacg/quicksilver#446]
I have a problem where I want to pass some initialisation data to my impl of `State`. This currently not possible because the only way to instantiate a struct that implements `State` is through the `new()` function that is called within `run`.

This can be fixed by adding a new `run_ex` function that allows the user to pass an existing `State` object which has already been initialized in a custom way. This should be done by moving the object so it's not possible to pass a `State` object that is already in use (as that would be by reference).
Other options include passing a lambda function to a new function `run_with` that instantiates the `State` and returns a `Result`. This allows passing of arguments by capturing them:
```rust
let arg1 = 0;
let arg2 = 1;
run_with("Title", (800, 600), Settings::default(), || MyState::new(arg1, arg2));
```

If a feature like this is desired I can start working on a pull request.

**Comment by ryanisaacg** [comment]
My question is why you would want to run any code before your state is instantiated? I'm curious about your use case.

**Comment by Kurble** [comment]
My use cases is integrated into a command line tool that requests some user input that needs 2D rendering (a map). I need to pass a filename to my state so it knows where to store the input. I'm not using web assembly for my current project.

My main concern is that the `State` trait is forced to be the *one and only* global state and there is no way to work around it, making it more difficult to integrate quicksilver in existing projects and environments.
