### ISSUE TITLE
Question : do you have or plan to support font rendering ?

### ISSUE THREAD

**Issue by Illthiriel** [ryanisaacg/quicksilver#46]
Hello,

sorry if it is not the good way of asking question :)

thanks

**Comment by ryanisaacg** [comment]
Font rendering is definitely something I want to add. Currently the plan is to add Bitmap font support (pre-rendered font characters in a texture) but if I find a good Rust font library I would tack on support for loading actual font files.

**Comment by Illthiriel** [comment]
great :)

**Comment by tomassedovic** [comment]
@ryanisaacg you're probably aware of this but just in case, there is a pure Rust font library that's used by Amethyst as well as Piston:

https://crates.io/crates/rusttype

**Comment by ryanisaacg** [comment]
@tomassedovic I wasn't aware actually, thanks for the heads up. A preliminary check shows that it builds for wasm which is a good sign

**Comment by tomassedovic** [comment]
\o/

By the way thanks for doing this. I can't wait to replace my cargo-culted opengl code with a good 2D graphics lib and quicksilver seems to be closest to what I need. Getting wasm as a bonus is almost too good to be true :-).

**Comment by ryanisaacg** [comment]
Glad to hear it! If you run into any problems feel free to open an issue.
