### ISSUE TITLE
List libasound2-dev as a dependecy 

### ISSUE THREAD

**Issue by aneeshdurg** [ryanisaacg/quicksilver#466]
Same issue as **https://github.com/ggez/ggez/issues/100** , install `libasound2-dev` resolves it.

**Comment by ryanisaacg** [comment]
Does installing `alsa` not resolve the problem?

**Comment by aneeshdurg** [comment]
No, some file is only provided by `libasound2-dev` or one of its dependencies.

**Comment by ryanisaacg** [comment]
Thanks! 👍
