### ISSUE TITLE
Event::Key(Key::Colon, ..) does nothing on web

### ISSUE THREAD

**Issue by rickyhan** [ryanisaacg/quicksilver#469]

**Comment by rickyhan** [comment]
Subtract is also not working.

**Comment by rickyhan** [comment]
This is the console!(log, keycode):

```
crabs.js:585 LShift
crabs.js:585 117
crabs.js:585 Minus
crabs.js:585 112
crabs.js:585 LShift
crabs.js:585 138
crabs.js:585 Semicolon
```

**Comment by ryanisaacg** [comment]
I'll take a look at that and hopefully get back to you soon, it's probably a keycode mapping failure. I should be able to fix it and push out a release with a fix within a week or so.

**Comment by ryanisaacg** [comment]
This should be solved on development right now, and in the next release (within the next few days.) Let me know if it's not!
