### ISSUE TITLE
Suggestion: Prelude

### ISSUE THREAD

**Issue by Silvea12** [ryanisaacg/quicksilver#470]
**Describe the problem you want to solve**
Starting a project with quicksilver always starts with me guessing what I'll need to even begin the thing. I say a prelude (like many other packages) would be very useful.

**Describe the solution you'd like**
A prelude containing types like vector, run, etc. Perhaps a couple types of prelude (main vs module) so you can have one that exports vector, rectangle, etc for sizing and other operations, and then one with main that has things like run, etc. If not a main one too, at least one for commonly used types.

**Are you interested in contributing?**
I would but I do not have enough experience to know what should and should not be included for the majority of games, I am still settling in. I may contribute this myself at a later date, but I cannot promise this.

**Comment by rickyhan** [comment]
I think it would be a good idea.

Here is mine:
```
pub use quicksilver::{
    geom::{Circle, Line, Rectangle, Transform, Triangle, Vector},
    graphics::{Background::Col, Color, Image},
    lifecycle::{Settings, State, Window, run, Asset},
};

pub use quicksilver::{
    Result, Error,
    combinators::{result, join_all},
    Future,
    load_file,
    geom::Shape,
    graphics::{Background::Img, Font, FontStyle},
    lifecycle::{Event},
    input::{ButtonState, MouseButton, Key},
    sound::Sound,
};
```

**Comment by ryanisaacg** [comment]
I'm not super familiar with prelude modules, but looking into them I quite like them. I also like @rickyhan's suggested preludes (though I may tweak them a bit).

I'll probably be able to get to adding the modules this week or next, and then they will be included in the next release.

**Comment by ryanisaacg** [comment]
So it ended up taking me slightly longer than a week: sorry about that! 😄 

School took up more of my time than I anticipated. Anyway, can you let me know if #479's prelude looks like what you were asking for?

**Comment by Silvea12** [comment]
@ryanisaacg Looks pretty good to me. Though seems line 7 in `prelude.rs` has an extra , that isn't meant to be there.

**Comment by ryanisaacg** [comment]
Alright, the 0.3.10 release contains the prelude!
