### ISSUE TITLE
Multiplayer networking for WASM and Desktop?

### ISSUE THREAD

**Issue by codec-abc** [ryanisaacg/quicksilver#474]
Hi,

Quick question here. I  would like to add support for network multiplayer in my game without dedicated server (now it only supports local multiplayer) . Does Quicksilver provides an API to abstract over network both for Desktop and WASM?

I think, in theory it could be feasible. For the desktop, I think I can use traditional TCP or UDP and WebRTC seems to allow peer to peer communications from what I [read on StackOverflow](https://stackoverflow.com/questions/4118272/do-websockets-allow-for-p2p-browser-to-browser-communication).

**Comment by ryanisaacg** [comment]
Quicksilver doesn't have any networking support and personally I'm not planning to add it. Possibly if you want to work on it, an external library would be best (so it's not tied to any specific framework,) or feel free to open a PR.

**Comment by codec-abc** [comment]
Thanks for the answer. Fair enough.
