### ISSUE TITLE
Mouse location on web is wrong when View size doesn't match Window size

### ISSUE THREAD

**Issue by Kurble** [ryanisaacg/quicksilver#477]
**Describe the bug**
I use a fixed 640x360 view so I can design my UI with absolute coordinates. When running my game in 1280x720 everything works fine on windows, but on the web the scale isn't applied to the mouse location.

**To Reproduce**
* Set your view to `View::new(Rectangle::new(Vector::ZERO, Vector::new(640.0, 360.0)))`
* Initialize the Window size as 1280x720
* Try to use mouse coordinates on the web

**Environment and versions:**
- Environment: wasm on firefox
- Rust compiler version: 2018
- Quicksilver verison: 0.3.7

**Comment by ryanisaacg** [comment]
I'll look into this and hopefully get a fix up soon.

**Comment by Kurble** [comment]
I just finished investigating this myself though!
The issue seems to be that in event.rs the mouse event is projected to view coordinates before the event is added to the buffer: 
```rust
glutin::WindowEvent::CursorMoved { position, .. } => {
    let position: Vector = position.into();
    let position = window.project() * (position - window.screen_offset());
    events.push(Event::MouseMoved(position));
}
```

while the same doesn't happen in run.rs, where the js bindings for the same thing are: 
```rust
handle_event(&canvas, &app, |mut app, event: PointerMoveEvent| {
        let pointer = Vector::new(event.offset_x() as f32, event.offset_y() as f32);
        app.event_buffer.push(Event::MouseMoved(pointer));
});
```

It may be a point of discussion which one of the two is the intended behaviour, but the first one seems logical to me. I'm going to submit a pull request right after pressing "comment".
