### ISSUE TITLE
`window.keyboard()[Key::Right].is_down()` does not work under 67.0b7 Firefox

### ISSUE THREAD

**Issue by Niedzwiedzw** [ryanisaacg/quicksilver#481]
**Describe the bug**
Releasing the arrow key in `camera.rs` example does not stop the camera from moving. Under chrome it works all right.

**To Reproduce**
run example under new firefox, i'm pretty sure it's os-independent.

**Environment and versions (please complete the following information):**
- Environment: Windows 10, Firefox
- Rust compiler version: rustc 1.35.0-nightly (acd8dd6a5 2019-04-05)
- Quicksilver verison: 0.3.11

**Comment by ryanisaacg** [comment]
I'm away from my Windows machine as of right now, but I can't get this to happen in Firefox 67b8 on my Mac test machine. I'll try it on Windows at some point tomorrow.

**Comment by Niedzwiedzw** [comment]
problem does not occur on 66.0.2 (64-bit) under windows, strange...

**Comment by ryanisaacg** [comment]
I can't repro this on Windows either. Is it still happening for you?

**Comment by ryanisaacg** [comment]
I'm going to close this for now, as it seems this is a regression in a specific version of Firefox. Feel free to re-open this if that is not the case.
