### ISSUE TITLE
Keyboard Press Not Registered on X11

### ISSUE THREAD

**Issue by ryanisaacg** [ryanisaacg/quicksilver#482]
**Describe the bug**

From gitter:

Quick question. I'm working on a quicksilver game on Linux (X11). I was checking for a keyboard press with window.keyboard()[Key::Return] == ButtonState::Pressed, but never get it. I printed it out every frame and see that the state goes from NotPressed to Held and back to NotPressed without ever going to Pressed or Released. This seems like a bug to me. How are you supposed to get just the Press event?
I tried checking for it through the State::event method, but I get repeat Press events. And see no way to disambiguate the first press from repeat ones.

**Environment and versions (please complete the following information):**
- Environment:  Linux X11

**Comment by Kurble** [comment]
Maybe related: I seem to be getting a lot of repeat `Pressed` events using the `Event` system, on macOS.

**Comment by ryanisaacg** [comment]
That probably shouldn't be related; desktop key presses all come from winit with very little processing within Quicksilver.

**Comment by ryanisaacg** [comment]
I do think this is a winit bug, and one that's probably fixed by the new versions of winit. Without further reports, I'll close this for now.
