### ISSUE TITLE
Can't compile `quicksilver` on asmjs-unknown-emscripten

### ISSUE THREAD

**Issue by EyeOfPython** [ryanisaacg/quicksilver#484]
I created a new crate with `cargo new hello --bin`, and added `quicksilver="0.3.11"` to Cargo.toml. I've also installed cargo-web with `cargo install cargo-web`.

When I run `cargo web start --target wasm32-unknown-unknown`, everything works fine, but when I run `cargo web start --target asmjs-unknown-emscripten`, I get the following error:

```
   Compiling slice-deque v0.1.16
error[E0432]: unresolved imports `libc::shmat`, `libc::shmctl`, `libc::shmdt`, `libc::shmget`
 --> /home/tobi/.cargo/registry/src/github.com-1ecc6299db9ec823/slice-deque-0.1.16/src/mirrored/sysv.rs:4:34
  |
4 |     c_int, c_void, mmap, munmap, shmat, shmctl, shmdt, shmget, shmid_ds,
  |                                  ^^^^^  ^^^^^^  ^^^^^  ^^^^^^ no `shmget` in the root
  |                                  |      |       |
  |                                  |      |       no `shmdt` in the root
  |                                  |      no `shmctl` in the root
  |                                  no `shmat` in the root

error: aborting due to previous error
For more information about this error, try `rustc --explain E0432`.
error: Could not compile `slice-deque`.

To learn more, run the command again with --verbose.
error: build failed
```

What is going on? Why does it need shared memory?

**Comment by ryanisaacg** [comment]
Quicksilver only supports the wasm32-unknown-unknown target, as per the readme. If I had to take a guess, it would be that all of the web-specific code is gated behind `target_arch = "wasm32"`, so asmjs fails. Is there a particular reason you want to compile with asmjs and emscripten?

**Comment by EyeOfPython** [comment]
> Is there a particular reason you want to compile with asmjs and emscripten?

It would be a graceful degradation for platforms that don't support WebAssembly yet, but support the canvas API.

**Comment by ryanisaacg** [comment]
Quicksilver uses WebGL 2.0 for its web graphics, which generally looks to be a subset of support for WebAssembly.

**Comment by EyeOfPython** [comment]
I see. Thanks!
