### ISSUE TITLE
More informative error propagation

### ISSUE THREAD

**Issue by paulirotta** [ryanisaacg/quicksilver#488]
**Describe the problem you want to solve**
Not all information from the source of an error makes it to the final error display
Example:
`thread 'main' panicked at 'Unhandled error: IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/quicksilver-0.3.11/src/lifecycle/state.rs:44:9
`
was due to missing `./static/font.ttf`
**Describe the solution you'd like**
Catch and propagate errors information from the source all the way down the chain

**Are you interested in contributing?**
I can take a look, but limited time and skill.

**Comment by ryanisaacg** [comment]
This has been in the back of my head for a little while, I'll definitely implement this when I get the chance.

**Comment by paulirotta** [comment]
I was thinking some repetitive pattern like `result.map_err(|e| SomeErr::from_string(format!("{:?}", e)))?` that preserves information as the error propagates outwards.

Thanks again!

**Comment by ryanisaacg** [comment]
The Asset API is gone, so it should be easier to figure out where an error comes from! Let me know if this is still an issue.
