### ISSUE TITLE
Provide modifier keys from WindowEvent::KeyboardInput in the Key event

### ISSUE THREAD

**Issue by hughlang** [ryanisaacg/quicksilver#490]
**Describe the problem you want to solve**

They Key enum currently provides the Key and the ButtonState as parameters. I would like it to include the modifier keys (e.g., shift, control, alt, logo) as either a bitwise parameter or an array so that I can provide more advanced keyboard operations.

See: https://docs.rs/winit/0.19.1/winit/struct.KeyboardInput.html

**Describe the solution you'd like**

Either modify Event::Key to include the modifiers parameter or add a new enum for KeyCombo or something like that. If you tell me your preference, I'm willing to do the code and PR.

**Are you interested in contributing?**

Yes. See also the bug report #489. I can take care of that too.

**Comment by ryanisaacg** [comment]
Currently for most instances you can poll the keyboard modifier state, but I agree it would be ideal to have the modifiers in the event itself.

To avoid excessive API breakage, I think the best option is to create a struct similar to winit's ModifierState and create a new event type with a name like `ModifiedKey` that contains the key, the button state, and the modifier state.

**Comment by ryanisaacg** [comment]
The new Event type from [`blinds`](https://github.com/ryanisaacg/blinds) has the modifiers stored with the Event. Check out the new alpha to use it.
