### ISSUE TITLE
Event enum does not implement PartialEq

### ISSUE THREAD

**Issue by mleprince** [ryanisaacg/quicksilver#491]
```an implementation of `std::cmp::PartialEq` might be missing for `&quicksilver::lifecycle::Event` ```

**Comment by ryanisaacg** [comment]
Do you have any context as to why you want to order Quicksilver events? I can't think of any meaningful way to order event instances.

**Comment by mleprince** [comment]
I needed it to compare two events  with `==` but I managed to do the comparaison with if let syntax.
I no longer need this partialEq implementation.

**Comment by ryanisaacg** [comment]
Ok, I’m glad this is resolved!
