### ISSUE TITLE
logical/physical pixels / HiDPI configuration

### ISSUE THREAD

**Issue by tehdarthvid** [ryanisaacg/quicksilver#492]
Pretty new at gamedev and rust so there's quite a bit to get caught-up on (but that's part of the point ;) ).
Is there a way to configure Quicksilver to use physical pixels instead of logical (or enable/disable hiDPI / related scaling)? Been looking but if it's there I'm missing it.
On a somewhat related topic, is there a way to control overall scaling?

**Comment by ryanisaacg** [comment]
There isn't any way to use physical instead of logical pixels currently, no.

For controlling how the window is resized, you might want to look at [`ResizeStrategy`](https://docs.rs/quicksilver/0.3.12/quicksilver/graphics/enum.ResizeStrategy.html)
