### ISSUE TITLE
Confusing tutorial example

### ISSUE THREAD

**Issue by nico-abram** [ryanisaacg/quicksilver#493]
https://docs.rs/quicksilver/0.3.12/quicksilver/tutorials/_06_asset_combinators/index.html imports and mentions using `result` but i see no use of it in the actual code.

**Comment by ryanisaacg** [comment]
You're totally right, that's a slip-up on my part. I'll get on that when I have the chance.

**Comment by ryanisaacg** [comment]
Fixed in 775c222c02911bbcb47f034e7b0eec94fe9f568e
