### ISSUE TITLE
Is there a way to list contents of a folder?

### ISSUE THREAD

**Issue by nico-abram** [ryanisaacg/quicksilver#494]

**Comment by ryanisaacg** [comment]
There is not; on desktop, you could do it with Rust's normal file system APIs. On the web, there is no way to expose this information.

**Comment by nico-abram** [comment]
There was a function to open a file on the web server iirc, couldn't something similar be done with a folder?

**Comment by ryanisaacg** [comment]
Given a path, you can make a web request, but there's no way (without support coded into the backend, which Quicksilver cannot assume) to list contents.

**Comment by ryanisaacg** [comment]
I think the question is answered, so I'll close this for now. Feel free to reply for more clarification, though!
