### ISSUE TITLE
Key Minus vs Subtract

### ISSUE THREAD

**Issue by moparisthebest** [ryanisaacg/quicksilver#498]
**Describe the bug**
It looks like the _/- key (on a qwerty keyboard between 0 and +/=) is `Subtract` as a native app but `Minus` running in the browser as WASM.

**To Reproduce**
Check [this commit](https://github.com/moparisthebest/oxi8/commit/1966cc5ee844a8b21bb16da2c4871d99fdfe7b23) for a quick example and to be able to reproduce.

**Environment and versions (please complete the following information):**
- Environment: Arch Linux, Firefox 66
- Rust compiler version: Rust stable 1.34.1
- Quicksilver verison: 0.3.12

**Comment by ryanisaacg** [comment]
Thanks for the report! I'll fix that by the end of this weekend hopefully.

**Comment by ryanisaacg** [comment]
It appears that the key between 0 and + on my Mac is reported as 'Minus' on my Mac, and I don't have any other machines to test on at the moment. I can try to set up a VM to reproduce, but no guarantees about time frame.

Can I ask what desktop environment you're running on?

**Comment by moparisthebest** [comment]
KDE 5.57

**Comment by ryanisaacg** [comment]
I would also consider reporting this upstream to the windowing library Quicksilver uses, [winit](https://github.com/rust-windowing/winit)

**Comment by ryanisaacg** [comment]
Quicksilver now exclusively uses Winit for key events, so if the issue persists please report it there.
