### ISSUE TITLE
Strange flickering when using Asset<Surface>

### ISSUE THREAD

**Issue by francesco-cattoglio** [ryanisaacg/quicksilver#501]
Hello there,
I am a Rust newbie and I am toying around with quicksilver, so pardon my noobness!
I found a strange behaviour trying to use asset combinators: the screen starts flickering like crazy when compiling a native binary, while a blank, non-flickering webpage is displayed if I give a `cargo web start` command. No text is displayed in either cases. I am using `rustc 1.35.0`, project is set to 2018 edition, quicksilver is version 0.3.13. 

Here is the minimal code to reproduce it on my side

```
// Test a funny behaviour
extern crate quicksilver;

use quicksilver::prelude::*;
use quicksilver::graphics::Surface;

struct Game {
    title: Asset<Image>,
    surface: Asset<Surface>,
}

impl State for Game {
    // Load the assets and initialise the game
    fn new() -> Result<Self> {
        // Square font by Wouter van Oortmerssen,
        // available at http://strlen.com/square/?s%5B%5D=font
        let font_mono = "square.ttf";

        let title = Asset::new(Font::load(font_mono).and_then(|font| {
            font.render("Just A Test", &FontStyle::new(72.0, Color::BLACK))
        }));

        let surface = Asset::new(Font::load(font_mono).map(|_font| {
            Surface::new(100, 100).expect("could not create a surface")
        }));

        Ok(Self { title, surface })
    }

    fn draw(&mut self, window: &mut Window) -> Result<()> {
        window.clear(Color::GREEN)?; // The screen will flicker using this color
 
        self.title.execute(|image| {
            window.draw(&image.area(), Img(&image));
            Ok(())
        })?;

        // if one comments out the following execute call, everything looks just fine
        self.surface.execute(|_surface| {
            // do nothing
            Ok(())
        })?;

        Ok(())
    }
}

fn main() {
    run::<Game>("Draw Geometry", Vector::new(800, 600), Settings::default());
}
```

The `title` Asset is not actually required for the flickering to happen. I know I am probably doing something wrong by using that `.map` on the `Font::load()` future, but I have not yet figured out what is going on exactly.
Just as a side note: what I am trying to achieve is loading a resource, compose it with some other geometry by rendering to a Surface, and then returning the composed image and storing it for future use.

**Comment by ryanisaacg** [comment]
For now, I would look into `join` and see if you can take the two futures and make them into one Asset. But I'll look into this when I have time, that is odd behavior you're describing..

**Comment by francesco-cattoglio** [comment]
Right, forgot that detail! I am on Kubuntu 19.04, my VGA is an integrated HD 630 with open source Intel drivers from Ubuntu repository.
WRT what I want to accomplish, `join()` followed by a `map()` should be enough, I agree.
