### ISSUE TITLE
Main lib file documentation missing linebreaks

### ISSUE THREAD

**Issue by zacharied** [ryanisaacg/quicksilver#503]
**Describe the bug**
The frontpage of the docs (in `lib.rs`) seems to have certain linebreaks removed, causing the Rust docstring sigil `//!` to appear as plaintext in the lines. An example:

<img width="965" alt="Screen Shot 2019-06-05 at 11 41 39 AM" src="https://user-images.githubusercontent.com/6374275/58970197-eb9fda00-8786-11e9-8b2b-918375d8825d.png">

This issue does not seem to be present in any of the other documentation, leaving me to believe the linebreaks were removed by mistake and not noticed. It's simple enough to fix but I wanted to run it by here to make sure it's not on my end.

**To Reproduce**
N/A

**Environment and versions (please complete the following information):**
N/A

**Comment by ryanisaacg** [comment]
That's a pretty nasty copy-paste issue,; thanks for catching that one. That's definitely not just on your end. If you want to submit a fix, I'd be grateful.

**Comment by zacharied** [comment]
I have submitted the PR. It also now correctly shows the logo at the top of the page -- that felt like too small of a problem to warrant its own issue.
