### ISSUE TITLE
Confused about drawing order

### ISSUE THREAD

**Issue by PhilipDaniels** [ryanisaacg/quicksilver#505]
I am not sure if this is a bug or not.

I wanted to draw a polygon. I eventually figured out that I had to use a mesh. My initial attempts were a complete failure as nothing appeared on the screen. I simplified it until I was able to see that the results appear to depend on the order that draw calls are made in.

The attached example draws a square mesh in black and a small image containing a red dot.

As the comment says, if I do this

```rs
// In this order we get the image but no polygon.
self.draw_image(window)?;
self.draw_poly(window)?;
```

the result is different compared to doing this:

```rs
// In this order we get both.
self.draw_poly(window)?;
self.draw_image(window)?;
```

Please, can you explain if there is a specific order that I have to draw things in? I have not seen it in the docs. Or is this a bug? Or are there any workarounds? I dug into the source code a little and noticed the `flush` method, calling that between the calls can fix the problem. But the docs say 'this is an expensive operation'.

[mesh.tar.gz](https://github.com/ryanisaacg/quicksilver/files/3269893/mesh.tar.gz)

**Comment by PhilipDaniels** [comment]
It may be related to #434

**Comment by ryanisaacg** [comment]
I'll take a look at this when I have time, that does sound like a bug though.

Flush sends the data from the CPU to the GPU and blocks while it does so, as well as handling all the Z-ordering at that point. As a workaround it should be fine until I can determine your issue.

**Comment by PhilipDaniels** [comment]
Thanks, I appreciate it. I'll go with flushing at the moment, I have plenty of other things to work on as well.

**Comment by ryanisaacg** [comment]
As in #434: This should be solved by the new alpha!
