### ISSUE TITLE
Can we implement `Asset<(A, B)>` for `(&mut Asset<A>, &mut Asset<B>)`? And etc.

### ISSUE THREAD

**Issue by rodya-mirov** [ryanisaacg/quicksilver#506]
**Describe the problem you want to solve**
Quite frequently I end up with very deep chains like: `assetA.execute(|assetA| { assetB.execute(|assetB| { assetC.execute(|assetC| // ...`

I don't like doing this, it makes the code hard to read (because of verbosity and indentation level), and wrecks the diff when I add or subtract an asset (because it makes the indentation level change).

**Describe the solution you'd like**
If we had a blanket implementation of Asset for tuples of Assets, it would be as simple as `(&mut assetA, &mut assetB, &mut assetC).execute(|a, b, c| { //...` which would be more compact, more readable, and etc.

For prior art, note that `specs` does this all over the place, and it is extremely ergonomic and pleasant. For example their tutorial: https://slide-rs.github.io/specs/08_join.html

**Are you interested in contributing?**
This seems simple enough that I might be able to do it myself, but I haven't contributed to open source before, so everything might be harder than I imagine.

**Comment by ryanisaacg** [comment]
That feature sounds great, feel free to go for it! If you need help, ping me and I'll try to get to it when I can.

**Comment by ryanisaacg** [comment]
The Asset API has been removed in the latest release, in favor of `.await` support.
