### ISSUE TITLE
Loading a jpg image causes a panic in WASM

### ISSUE THREAD

**Issue by francesco-cattoglio** [ryanisaacg/quicksilver#508]
**Describe the bug**
Loading a jpg file in wasm build causes a panic.

**To Reproduce**
Run the image.rs example, but instead of loading a png, try loading a jpg (such as the attached one) and run with `cargo web start`
![image](https://user-images.githubusercontent.com/6145579/60027363-9a0bb080-969d-11e9-9233-6a34a35af215.jpg)
Running the example in native build will work with no issues instead.

**Environment and versions (please complete the following information):**
- Environment: Ubuntu + Firefox, but it should not matter
- Rust compiler version: Rust stable 1.35
- Quicksilver version: latest

**Notes:**
I tracked down the origin of the problem, and it lies in the `jpeg-decoder` package: by default it uses rayon, but rayon is not fully supported by wasm yet: it does compile, but it panics on usage. See also https://github.com/image-rs/image/issues/879 and https://github.com/image-rs/image/pull/724

It *should* be really easy to fix, just by modifying the `Cargo.toml`. However when I tried playing around with my local quicksilver version, no matter what changes I did to `Cargo.toml`, they were ignored, so I was unable to create a fix... sorry, I am still a rust noob! :stuck_out_tongue: 
OTOH, if I use my fork of `jpeg-decoder` and manually disable the code path using rayon, everything works, so I am 100% confident: usage of rayon in the `image`/`jpeg-decoder` package is the source of the panic.

**Comment by ryanisaacg** [comment]
That is indeed a problem! I guess the way to fix that is to disable Rayon in `image` on web targets. At some point this week I'll try to take a look and get a fix out for that.

**Comment by nycex** [comment]
Also happens to me with ttf fonts
