### ISSUE TITLE
State::new is redundant when using lifecycle::run_with

### ISSUE THREAD

**Issue by nico-abram** [ryanisaacg/quicksilver#510]
What the title says. Putting new in a separate trait and using it as a bound on run but not run_with I think would deal with it.

I personally think lifecycle::run is redundant and not needed (Using run_with should cover that case without issues, and imo read better).

**Comment by Kurble** [comment]
The `run_with` function was introduced as a workaround for `State::new()`, so that makes sense.
I agree that `State::new` is redundant, but I don't think that `lifecycle::run` is redundant. It's there for it's own reasons.

**Comment by ryanisaacg** [comment]
I agree, but changing this would be a breaking change and the next breaking change (async / await support) will likely remove the State API anyways. I'll leave this open for now, just in case I change direction on the async / await life cycle API.

**Comment by ryanisaacg** [comment]
The State API has been removed, in favor of the async / await API.
