### ISSUE TITLE
Image::from_raw not working in wasm target

### ISSUE THREAD

**Issue by nico-abram** [ryanisaacg/quicksilver#512]
The following example: 
```

struct GameState {
  x: Box<[u8; 240 * 160 * 3]>,
}

impl State for GameState {
  fn new() -> Result<Self> {
    unimplemented!()
  }

  fn draw(&mut self, window: &mut Window) -> Result<()> {
    window.clear(Color::WHITE)?;
    for idx in 0..(240 * 160) {
      self.x[idx * 3 + 0] = self.x[idx * 3 + 0].overflowing_add(4).0;
      self.x[idx * 3 + 1] = self.x[idx * 3 + 1].overflowing_add(5).0;
      self.x[idx * 3 + 2] = self.x[idx * 3 + 2].overflowing_add(6).0;
    }
    let img = Image::from_raw(&self.x[..], 240, 160, PixelFormat::RGB)?;
    window.draw(&img.area(), Img(&img));
    Ok(())
  }
}
fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
  quicksilver::lifecycle::run_with("Test", Vector::new(240, 160), Settings::default(), || {
    Ok(GameState { x: Box::new([0u8; 240 * 160 * 3]) })
  });
  Ok(())
}
```
Flashes the screen in different colours on desktop (window 64 bit target) when I run it with "cargo run". However, when I run it with "cargo web start" and open it in the browser, I get a constant black image.

**Comment by ryanisaacg** [comment]
That's very odd, because from_raw is how all images are created! Can you check your developer console in the browser and paste any errors? That will help me out when I have time to look into this.

**Comment by nico-abram** [comment]
This is the output from the firefox console:
https://i.imgur.com/rXctj3R.png
https://i.imgur.com/69oAm9l.png
This is what it looks like: https://i.imgur.com/NCdEspb.png

**Comment by nico-abram** [comment]
I just tried it on chrome: https://i.imgur.com/DM0Rd3K.png (Same black image output).

I tried this, which is just a white image on the windows target, and I also got a black image in the browser:
```rs

  fn draw(&mut self, window: &mut Window) -> Result<()> {
    window.clear(Color::WHITE)?;
    let mut a = [255u8; 240 * 160 * 3];
    let img = Image::from_raw(&a[..], 240, 160, PixelFormat::RGB)?;
    window.draw(&img.area(), Img(&img));
    Ok(())
  }```

**Comment by nico-abram** [comment]
Update: Using RGBA seems to work. But it's a bit annoying since I have to convert my data.

**Comment by ryanisaacg** [comment]
I have a couple hunches about what could cause the issue (incorrect calls to webgl in the backend maybe?), but if RBGA is fixing it for now I'd say go for that because I'm not sure when I'll have the time to dig into this.

**Comment by paulirotta** [comment]
There is an apparently related problem in 0.3.22 loading image in WASM. I backported this fix and it works (with a slightly older version of IMAGE dependency), but only for PNG not JPG in my tests.

I'll put that PR in separately. The change is:

image = { version = "0.21", default-features = false, features = ["png_codec", "jpeg"] }

**Comment by ryanisaacg** [comment]
`Image::from_raw` shouldn't be interacting with the `image` dependency; are you sure that the root cause is the same?

**Comment by paulirotta** [comment]
I'm not sure. It appears as a decoding error in WASM only and the solution was similar so perhaps a common upstream code generation error is to blame.
