### ISSUE TITLE
Key presses get repeated

### ISSUE THREAD

**Issue by 42triangles** [ryanisaacg/quicksilver#523]
**Describe the bug**
The documentation for `ButtonState::Pressed` states that it *only* gets triggered, if they key was pressed in this frame. However, after a slight delay with the button still being held, this events gets spammed. (like in a text field when pressing a button long enough)

So this is either an implementation bug, or a documentation mistake (in which case it would make sense to provide a way to disable key repetition).

**To Reproduce**
```rust
use quicksilver::{geom::Vector, input::ButtonState, lifecycle::{Event, State, Window, run}, Result};

struct App;

impl State for App {
    fn new() -> Result<Self> {
        Ok(App)
    }

    fn event(&mut self, event: &Event, _: &mut Window) -> Result<()> {
        match event {
            Event::Key(_, ButtonState::Pressed) => println!("pressed"),
            _ => (),
        }

        Ok(())
    }
}

fn main() {
    run::<App>("Test", Vector::new(640, 480), Default::default());
}
```

**Environment and versions (please complete the following information):**
- Environment: Arch Linux under i3
- Rust compiler version: `1.37.0-nightly (991c719a1 2019-06-08)`
- Quicksilver verison: 0.3.18

**Comment by ryanisaacg** [comment]
That's a doc error, ButtonState::Pressed occurs once in the key state, not the events (so exactly one `update` will execute where `window.keyboard()[MyKey]` is equal to `ButtonState::Pressed`). Probably a good option is to use a different enum from ButtonState in the events.

Do key repeats for events interfere with your use-case?

**Comment by 42triangles** [comment]
They do, since jumping in my game reacts to starting the button press (starting the jump), and letting go (falling straight down).

The workaround I then used was keeping track of whether or not the button was already released, which honestly feels kind of hacky.

**Comment by ryanisaacg** [comment]
I'm going to be re-working the lifecycle system for async / await, so I'll catch repeated keypresses in the new design.

**Comment by ryanisaacg** [comment]
The new (0.4.x) API doesn't differentiate between 'this key is held down' and 'this key has just been pressed;' the way to do that now is to simply listen for key events. That should resolve this issue going forward.
