### ISSUE TITLE
Touch input only works in certain browsers

### ISSUE THREAD

**Issue by jakmeier** [ryanisaacg/quicksilver#526]
Hello, and thank you for your work on this crate, it has been of great help for me and very easy to use!

I have a minor bug report, affecting the wasm target and only in certain browsers.
A PR with a suggestion for a fix will follow.

**Describe the bug**
In some mobile browsers, a touch input does not trigger any quicksilver events, as it would be expected since #429 has been merged and #366 closed.
The problem with the current implementation is that it relies on PointerEvents from the browser such as [pointermove](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointermove_event) and [pointerdown](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointerdown_event). Unfortunately, these events are not implemented by all mobile browsers.

The result is that nothing happens on touching the screen, when using an affected browser, while in others a MouseClick / MouseMove event is triggered. 

**To Reproduce**
The best way to reprocude is with Firefox on mobile and WebIDE, printing all events to the console.
Firefox has an option in about:config called `dom.w3c_pointer_events.enabled`. Without reloading, changing this flag will either show mouse click events on touches or not.

**Environment and versions (please complete the following information):**
- Environment: Problem occurs in these browsers:
    - Firefox on Android, version >= 29 (with default settings)
    - Safari on iOS
    - Samsung Internet
    - *Maybe also in Opera for Android*
- Rust compiler version: *Not relevant, bug is specific to web* 
- Quicksilver version: latest (0.3.18)

**Solution:** 
I have already a local branch which fixes this bug. I will reference this issue and submit a PR immediately.

**Comment by jakmeier** [comment]
I forgot to mention it above but actually the touch input seemed to be buggy in all browsers before. The mouse position on the quicksilver window has not been updated on a PointerDown event, therefore the click event provided by quicksilver has not really been useful since the correct position is inaccessible at this point. (When a finger taps the screen at a single location, no MoveEvents are generated)

Since I figured this out while fixing the other issue, I forgot to mention it. But it is probably the bigger problem since it affects more browsers.

#527 fixes both bugs

**Comment by ryanisaacg** [comment]
Closing in favor of https://github.com/rust-windowing/winit/issues/1286, because future versions of Quicksilver will be using Winit's web backend instead of its own.
