### ISSUE TITLE
Surface::render_to must be marked as unsafe

### ISSUE THREAD

**Issue by Lokathor** [ryanisaacg/quicksilver#529]
https://docs.rs/quicksilver/0.3.18/quicksilver/graphics/struct.Surface.html#method.render_to

> Do not attempt to use the surface or its image within the function, because it is undefined behavior

So you gotta mark this as an `unsafe` function.

**Comment by ryanisaacg** [comment]
Good point, and I'll make this a safe abstraction when I get to re-working the graphics system.
