### ISSUE TITLE
How to apply a transform to a mesh

### ISSUE THREAD

**Issue by ForsakenHarmony** [ryanisaacg/quicksilver#532]
It's not really obvious to me how to apply a transform to a mesh when drawing

I'd like to draw the same mesh in different positions (translate, possibly rotate it)

**Comment by ryanisaacg** [comment]
I'm sorry to say that currently there isn't a great built-in way to do that. You could create a custom `Drawable` that wraps a mesh and uses the supplied transform as a solution.

I plan to clean this up in the next major API revision but that might not be in the near future.

**Comment by hughlang** [comment]
You can manipulate a mesh position like this:

```
  for (_, vertex) in mesh.vertices.iter_mut().enumerate() {
      vertex.pos = Transform::translate(self.offset) * vertex.pos;
  }
```	

And you can freely clone meshes and apply transforms. Is this what you need?

**Comment by ryanisaacg** [comment]
Check out the `Graphics::set_transform` function in the new alpha! It should allow you to apply a transform to a mesh draw.

**Comment by ForsakenHarmony** [comment]
Could you write the changes into github releases (as well)?

**Comment by ryanisaacg** [comment]
Sure, [just did](https://github.com/ryanisaacg/quicksilver/releases/tag/v0.4.0-alpha0)
