### ISSUE TITLE
Best way to detect on which image I clicked.

### ISSUE THREAD

**Issue by Pfeil** [ryanisaacg/quicksilver#533]
Assume that I have a lot of images (thumbnails) displayed, some may partially overlap. My intuitive way of a "I clicked on image X" output would be to give every image a shape, give my cursor a shape, and loop over all shapes to see if there are collisions if I clicked. But this sounds heavy for a lot of images. Are there any other built-in mechanisms that I missed? Would my approach be the way to go? I know I could use a quadtree to reduce the number of shapes I have to check, but I am interested in the possibilities and ergonomics that are built-in.

**Comment by ryanisaacg** [comment]
If you're seriously worried about performance and have a truly large number of images (somewhere in the thousands? tens of thousands?) you may want to look into the `ncollide` crate for efficient collision checking.

The naïve approach of sorting the shapes where the first rect is the most on top and the last rect is the most on bottom, and just checking each in order should probably be fine for most use cases though.

**Comment by Pfeil** [comment]
Thanks for your answer. My needs are currently still under 10.000, but it may increase. I think I missed the point of my actual question when I wrote this, sorry. I read about ncollide support, but I thought this would enable the overlap method and so on. Diving into the code, I just saw that this enables actually conversion to ncollide AABBs (Does it more than that?). I'll take a look at it, thanks.

To come to my actual point: I modified a few examples and searched the docs and came to a conclusion, where I am not sure if it is correct and sound in respect to quicksilver. This is my conclusion, I wonder if it is correct:

Shapes can check for overlap (or be used with ncollide). Images can not. So I have to maintain a shape for each image and use them to check (like a collision mesh). There is no other (practical) way in quicksilver. There is no event based method per shape (or image) but a global input event. I have to check manually (naively, by sorting, using quadtree or ncollide) how the mouse collides with shapes. I read that in general there are tricks like second render passes and things like that, but I assume this is not supported by quicksilver.

Is this correct? I am sorry I wasn't precise in the first place.

**Comment by ryanisaacg** [comment]
> Diving into the code, I just saw that this enables actually conversion to ncollide AABBs (Does it more than that?). I'll take a look at it, thanks.

Yup, ncollide support is just support to convert to ncollide types. All the overlap methods are built in to Quicksilver.

> . I have to check manually (naively, by sorting, using quadtree or ncollide) how the mouse collides with shapes. I read that in general there are tricks like second render passes and things like that, but I assume this is not supported by quicksilver.

That's correct, yeah.

Let me know if you have any more questions!

**Comment by Pfeil** [comment]
This question is pretty much solved. It was mostly about the available API. Thank you! :+1:
