### ISSUE TITLE
[Question] [2D] Documentation for off-screen rendering?

### ISSUE THREAD

**Issue by klemmm** [ryanisaacg/quicksilver#537]
Hello,

Could you provide in the documentation/tutorial an example using the off-screen rendering (i.e. render stuff to a Surface, then get the image from the Surface) ? I did not find any (my apologies in the case I missed it).

Thank you in advance.

**Comment by ryanisaacg** [comment]
Unfortunately there aren't great docs for off-screen rendering with the current version, and it generally doesn't work very well. Upcoming in the next major version will be a better off-screen rendering API and more documentation on how to use it. You can check out the [Surface docs](https://docs.rs/quicksilver/0.3.20/quicksilver/graphics/struct.Surface.html) for now in the meantime.

**Comment by ryanisaacg** [comment]
The new graphics API now has [an example](https://github.com/ryanisaacg/quicksilver/tree/master/examples) that renders to a Surface, and then uses its Image. Let me know if you have any more questions, and feel free to re-open if necessary.
