### ISSUE TITLE
Gamepad ButtonState constantly reset to ButtonState::Released

### ISSUE THREAD

**Issue by MaulingMonkey** [ryanisaacg/quicksilver#538]
**Describe the bug**
Gamepad ButtonState is constantly reset to Released, when it should only be set for a single `update` after a `Pressed` -> `Held`xN chain.

**To Reproduce**
1. Write and run a state such as:
```rust
use quicksilver::prelude::*;

struct Example;

impl State for Example {
    fn new() -> Result<Self> {
        Ok(Self)
    }

    fn update(&mut self, window: &mut Window) -> Result<()> {
        for gamepad in window.gamepads() {
            assert!(gamepad[GamepadButton::DpadUp] == ButtonState::NotPressed);
        }
        Ok(())
    }
}

fn main() {
    run::<Example>("Example", Vector::new(800, 600), Settings::default());
}

```
2. Have a gamepad connected, but press no buttons
3. Assert anyways when the state transitions from ButtonState::NotPressed -> ButtonState::Released

**Environment and versions (please complete the following information):**
- Environment: Windows 10
- Rust compiler version: 1.39.0
- Quicksilver verison: 0.3.20

**Code Dive:**
update_gamepads_impl creates a Released state from thin air here: https://github.com/ryanisaacg/quicksilver/blob/5d4b0a098bdc1468a0a7775e11c75dd69a65df56/src/lifecycle/window.rs#L233-L234

Which is stuffed into gamepad_buffer:  https://github.com/ryanisaacg/quicksilver/blob/5d4b0a098bdc1468a0a7775e11c75dd69a65df56/src/lifecycle/window.rs#L215

Because NotPressed and Released are both is_down(), set_previous doesn't modify the copy in gamepad_buffer here in update_gamepads:
https://github.com/ryanisaacg/quicksilver/blob/5d4b0a098bdc1468a0a7775e11c75dd69a65df56/src/lifecycle/window.rs#L189

Finally, the NotPressed in gamepads is overwritten with the Released in gamepad_buffer here: https://github.com/ryanisaacg/quicksilver/blob/5d4b0a098bdc1468a0a7775e11c75dd69a65df56/src/lifecycle/window.rs#L200-L201

**Comment by ryanisaacg** [comment]
Thanks for the report and the code dive! I'll try to get a patch out for this soon.

**Comment by MaulingMonkey** [comment]
Confirmed fixed in the current `development` branch.
