### ISSUE TITLE
I can not build quicksilver-next branch

### ISSUE THREAD

**Issue by skhello27** [ryanisaacg/quicksilver#542]
Hi,
I am trying to 'cargo web build' quicksilver-next branch just to look inside. 

Cargo.toml of my project: 
<pre>
[dependencies]
quicksilver = { path = "../quicksilver-next/", features = ["stdweb"] }
</pre>

Rust is latest stable, OS is Ubuntu 16.04

Errors:
<pre>
warning: unused import: `objects::*`
  --> /home/karasiov/RUST/quicksilver-next/src/graphics.rs:17:39
   |
17 | use golem::{*, buffer::*, program::*, objects::*};
   |                                       ^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `run as _`
   --> /home/karasiov/RUST/quicksilver-next/src/lib.rs:149:26
    |
149 |     use blinds::{run_gl, run as _};
    |                          ^^^^^^^^

error[E0061]: this function takes 0 parameters but 4 parameters were supplied
  --> /home/karasiov/RUST/quicksilver-next/src/graphics.rs:81:18
   |
81 |         self.ctx.clear(color.r, color.g, color.b, color.a);
   |                  ^^^^^ expected 0 parameters
error[E0599]: no method named `id` found for type `std::rc::Rc<golem::objects::Texture>` in the current scope
   --> /home/karasiov/RUST/quicksilver-next/src/graphics.rs:118:66
    |
118 |             (Some(image), Some((_, Some(old_image)))) => image.0.id() != old_image.0.id(),
    |                                                                  ^^ private field, not a method
error[E0599]: no method named `id` found for type `std::rc::Rc<golem::objects::Texture>` in the current scope
   --> /home/karasiov/RUST/quicksilver-next/src/graphics.rs:118:86
    |
118 |             (Some(image), Some((_, Some(old_image)))) => image.0.id() != old_image.0.id(),
    |                                                                                      ^^ private field, not a method
error: aborting due to 3 previous errors

</pre>

**Comment by ryanisaacg** [comment]
Hi, `quicksilver-next` is pretty far from usable currently! It's public for two main reasons:

- I'm syncing it between multiple of my own machines while developing
- People can see the general direction the next version is moving towards

When `quicksilver-next` is closer to usable, I'll be publishing a series of alpha and beta versions leading up to the full release.

**Comment by ryanisaacg** [comment]
The first alpha release is the being published in #553
