### ISSUE TITLE
Should I upstream quicksilver.natvis?

### ISSUE THREAD

**Issue by MaulingMonkey** [ryanisaacg/quicksilver#544]
I'm experimenting with making .natvis stuff easier to use from Rust and wrote a visualizer for `Event`s.  Would you like to see pull requests for such things?  https://gist.github.com/MaulingMonkey/528776ae44bbf247d9d9801c529f0fd3  (For my own needs, I've got a utility crate I can just dump this in, so it's fine if you're not interested.)

It's pretty brittle, and eventually (tm) I'd like to see it replaced by natvis files autogenerated by rustc - but I have no idea how long it'll be until such a thing is done.

If included in the crate alongside Cargo.toml, or directly inside src, [natvis-pdbs](https://github.com/MaulingMonkey/natvis-pdbs) would be able to find and embed it into `.pdb`s when natvis-pdbs is used in the build script of quicksilver executables.  If you've got ideas for other places nativs-pdbs should search, I'm open to suggestions - although I'm trying to avoid arbitrary recursion in the interest of build times...

**Comment by MaulingMonkey** [comment]
(Oh, and I should note I'm guessing on the layout of some of these events as I couldn't generate them with 0.3.20 on windows 10 - fortunately they're all types with "obvious" layouts:)

### Untested

* Closed (maybe generated, I can't recall if I tested it)

### Not generated

* Focused/Unfocused
* MouseEntered/MouseExited
* GamepadConnected/GamepadDisconnected

### Tested

* Key
* Typed
* MouseMoved/MouseWheel/MouseButton
* GamepadAxis/GamepadButton

**Comment by ryanisaacg** [comment]
Sorry, to be honest I have no idea what natvis is?

**Comment by MaulingMonkey** [comment]
Natvis files are used to customize debug views for Microsoft debuggers.  So, for example, here's what VS Code shows me without any custom debug visualizers for a `Event::GamepadButton(0, GamepadButton::DpadDown, ButtonState::Pressed)` event - only the `RUST$ENUM$DISR` field is remotely accurate, with the `__0` ..= `__2` fields being of the wrong types / offsets entirely corresponding to other enum cases:

![image](https://user-images.githubusercontent.com/75894/70002815-0eccfb80-1516-11ea-86d9-36f49f2b1515.png)

vs. with quicksilver.natvis:

![image](https://user-images.githubusercontent.com/75894/70002820-12608280-1516-11ea-8eb9-6caa7e4e25ba.png)

**Comment by MaulingMonkey** [comment]
(They also work in VS, WinDbg, CDB, KDB, and who knows what else Microsoft has written!)

**Comment by ryanisaacg** [comment]
For now, I would probably say that this is interesting but probably not great to upstream. I do think teaching rustc to emit the info is probably the best path forward in general.

**Comment by MaulingMonkey** [comment]
Fair enough, I'll close this issue 👍
