### ISSUE TITLE
Portable console logging

### ISSUE THREAD

**Issue by johnpmayer** [ryanisaacg/quicksilver#545]
I found the following helpful and am wondering if it would be considered for inclusion somewhere in the library. Thoughts? I can imagine making it a bit more feature-rich, this is just the bare minimum.

``` rust
#[macro_export]
macro_rules! portable_log {
    ($($arg:tt)*) => ({
        #[cfg(target_arch = "wasm32")]
        console!(log, "{}", format!($($arg)*));
        #[cfg(not(target_arch = "wasm32"))]
        println!($($arg)*);
    })
}

```

**Comment by ryanisaacg** [comment]
I think that this could be useful, but generally I would say the best practice would be to use [`log`](https://docs.rs/log/0.4.8/log/) with different backends. For example, the [`console_log`](https://docs.rs/console_log/0.1.2/console_log/) crate works well for wasm-bindgen, so a single log backend that works for both desktop and stdweb could be an interesting standalone crate.

**Comment by ryanisaacg** [comment]
Quicksilver 0.4 includes integration with `log` as a default (but optional) feature, so you can use `log::error!`, `log::warn!`, etc. This should make portable logging much easier.
