### ISSUE TITLE
How to Find Screen Edges with ResizeStrategy::Fill

### ISSUE THREAD

**Issue by jeorb** [ryanisaacg/quicksilver#550]
What is the best way to read the window size and offset when using ResizeStrategy::Fill?

I use ResizeStrategy::Fill with a square world size so that my game fills the screen in portrait or landscape aspect ratios.  This works great for the gameplay elements because the focus is the center of the screen so trimming off the edges doesn't hurt anything.  However, this does not work well for UI elements at the edges of the screen.

I'd like read the screen size so I can position ui elements to stay at the edges in any aspect ratio and reposition the elements if the screen size changes (window resize or a phone rotating from portrait to landscape).

I found Window::screen_size() which returns the width and height of the full virtual area which can be scaled to screen units using the projection matrix but I don't see a way to get the screen offset which would also be needed to compute the actual screen size and the location of the edges of the screen.  There is a Window.screen_offset function but the access is set to pub(crate).

**Comment by ryanisaacg** [comment]
Unfortunately the current ResizeStrategy API actually can't let you draw in the margins, because it constrains the drawable space rather than just setting a projection. Changing this is part of an upcoming major graphics API rework, actually!

**Comment by jeorb** [comment]
I may be using unintentional feature to achieve the behavior I was looking for.  By using ResizeStrategy::Fill with a square aspect ratio, Quicksilver lets me draw to the full square area and it trims off whatever doesn't fit on the screen.

This illustration shows how I am using this:

![ResponsiveLayout](https://user-images.githubusercontent.com/2908808/73145099-166dd400-4071-11ea-81ab-5915628c9751.png)

I have no idea if what I am trying to do is a good idea but maybe this can serve as a use case.

Thanks for everything!

**Comment by ryanisaacg** [comment]
I think this means the issue is resolved and good to close? Feel free to re-open to discuss anything else.
