### ISSUE TITLE
logging isn't initialized

### ISSUE THREAD

**Issue by johnpmayer** [ryanisaacg/quicksilver#569]
feature is "easy-log" with a dash, but code guards on "easy_log"

I'll open a PR at some point... really sucks that this isn't some sort of compiler error

**Comment by ryanisaacg** [comment]
Oop, thanks for catching that. Yeah, I'm surprised it's allowed to guard on impossible features.

**Comment by ryanisaacg** [comment]
Fixed in 4a020108b5c051c8f1a4e53d6d7262ffc5383d8b, thanks again for the report
