### ISSUE TITLE
Question: The texture width was not a power of 2

### ISSUE THREAD

**Issue by johnpmayer** [ryanisaacg/quicksilver#570]
This looks like it's coming from golem/texture.rs

I'm trying to setup a sprite sheet for animation, and while my source image file (PNG, RGBA) consists of many regular power-of-two (32x32) sprites, collectively they are on an irregularly sized image file (multiples of 32, but not themselves power of 2, e.g. there are 13 columns of sprites, so the image is 416 pixels wide).

I was hoping to load an image once, and then use `Graphics::draw_subimage` while rendering.

I see that golem/texture's documentation for `Texture::set_image` says "If they are both powers of 2, mipmaps will be generated. If they aren't, mipmaps will be unavailable." However, the program panics, probably because of those asserts.

Mostly asking about intent of that API. I'm expecting that I can work around the image by "extending" the size of my sprite sheet to be something like 512x512.

**Comment by ryanisaacg** [comment]
Those asserts aren't necessary after https://github.com/ryanisaacg/golem/commit/34503229d0ccfbce0fbf5d59959f664781654e3d, I'll remove them and publish a new golem version when I get a chance.

Mipmaps are only available when using a base texture that's power-of-two sized, but if you don't need mipmaps then your usage of the API is perfectly fine.

**Comment by elsassph** [comment]
Potentially useful to get a warning when loading an image that isn't power of 2?

**Comment by ryanisaacg** [comment]
Not sure if that would be necessary; if you're not mipmapping or using repeated textures, there's no issue. Also, if you try to do either, you'll immediately get an error.

**Comment by ryanisaacg** [comment]
There's a new golem version out, which should solve this. For now you should be able to just `cargo update`, and get the new changes. After #572 lands in a release, you'll be updated to the newer golem version automatically.
