### ISSUE TITLE
impl Sum for geom::Vector

### ISSUE THREAD

**Issue by vorner** [ryanisaacg/quicksilver#573]
**Describe the problem you want to solve**

I wanted to do some little bit of physics (gravity between bunch of objects in space). When computing the gravity pull to one object, all others provide their own partial gravity pull and in the end I have to sum them up to get the total.

Now I have to do a for-cycle and manually do `total += partial`. It would be more convenient to do eg `.map(..).sum()`, but the trait is not implemented.

**Are you interested in contributing?**

If you find it an acceptable idea, I can send the pull request, I just wanted to check first before I go and implement it. Would it be OK?

**Comment by ryanisaacg** [comment]
That sounds good, feel free to submit a PR!
