### ISSUE TITLE
Implement addition and subtraction for Transform

### ISSUE THREAD

**Issue by paulirotta** [ryanisaacg/quicksilver#575]
**Describe the problem you want to solve**
I needed to implement an easing function to get 60fps smoothing interpolation of SVG mutations. These calculations may take the form ´end + (start-end)*percent´ where percent is ´0.0..1.0´ and the other values are type Transform.

I have done this in an own fork for quicksilver 0.3 but would like to update to stock 0.4 in the future. A working example is posted at https://github.com/N-of-1/mandala_quicksilver

**Describe the solution you'd like**
Implement Add and Sub on the Transform matrix, with unit tests

**Are you interested in contributing?**
I will submit a PR against this request soon.

**Comment by ryanisaacg** [comment]
I'm not sure using add / sub directly on Transform matrices will produce a smooth interpolation. Generally I believe best practice is to interpolate between the given scale, rotation, and translation and then generate the Transform from that. Is that applicable/possible for your use case?

**Comment by paulirotta** [comment]
It does work at 60fps. Sample run on Jetson Nano- visible CPU bar at bottom indicates the work is not too heavy: https://photos.app.goo.gl/64pg414WCij6rERs5

WIP code at https://github.com/N-of-1/mandala-quicksilver does not work on WASM yet due to various issues.

Linear interpolating colors gives more surprising results. Perhaps a different approach- interpolation need not be linear.

The PR failed only on nightly. Beta might be a more stable choice.

**Comment by ryanisaacg** [comment]
My concern wasn't smoothness as in performance, but smoothness as in a constant interpolation factor. If the results you get with interpolating the matrices directly works for you, though, I'd be happy to merge the PR.
