### ISSUE TITLE
Example of starting the application without `lifecycle::run`

### ISSUE THREAD

**Issue by vorner** [ryanisaacg/quicksilver#579]
**Describe the problem you want to solve**

All the examples and documentation (in the 0.4-alpha branch) suggest to start the game by `lifecycle::run`. While convenient to start developing quickly, I feel like this might be somewhat limiting, for several reasons:

* Completely disallows any kind of window management. It is possible one would want to have more than one window, or start with a splashscreen/progress bar and launch the main game window later on. This way, one gets the main window and not much can be done about it.
* The enforced error type is not really generally suitable, as it doesn't much allow for custom errors or different ways than printing the debug representation of the returned error to a log.

**Describe the solution you'd like**

I've looked into the source code of the `run` function and it doesn't seem to be too complex or to use any private parts of the library. Furthermore, if some parts (eg. creation of the window or such) were split off into some other (public) functions, it would be even simpler. Then it would be nice to have one example for doing a more complex setup.

I'd still think it makes sense to keep most of the examples and documentation using `run` as it is the quick way to start.

**Are you interested in contributing?**

Maybe. I might try putting something together, but I'd still want to consult the resulting interface.

**Comment by ryanisaacg** [comment]
Window management is outside the scope of Quicksilver, because it complicates the design greatly for the general case. I can see a design for creating multiple windows that exist for the application’s lifetime not adding too much complexity, but I don’t think dynamically creating or destroying windows would be worthwhile.
It is entirely possible though to have a progress bar on your main window, before you launch into your application’s logic. This could be a good candidate for an example.
Allowing custom error types or error handling behavior could be useful for some cases without a great deal of maintenance burden, do you have any thoughts as to a design there?

**Comment by vorner** [comment]
> It is entirely possible though to have a progress bar on your main window, before you launch into your application’s logic. This could be a good candidate for an example.

I was thinking in the form of smaller splash screen before loading everything and switching to fullscreen thing. I haven't played many games lately, but in my younger days things like C&C Generals and Warcraft III had these. Maybe the resize/fullscreen can be done on the existing window too, though.

> Allowing custom error types or error handling behavior could be useful for some cases without a great deal of maintenance burden, do you have any thoughts as to a design there?

Two possibilities come to mind here, in addition to just leaving the user to build the window and everything by hand.

* Providing some all-encompassing error type and actually returning it from `run` instead of doing the logging in there. One thing I use sometimes is simple `type AnyError = Box<dyn std::error::Error + Send + Sync>`.
* Make the error a type parameter, bound by something like:
```rust
where
  E: std::error::Error,
  quicksilver::Error: Into<E>,
```

**Comment by ryanisaacg** [comment]
> I was thinking in the form of smaller splash screen before loading everything and switching to fullscreen thing. I haven't played many games lately, but in my younger days things like C&C Generals and Warcraft III had these. Maybe the resize/fullscreen can be done on the existing window too, though.
Yup, you can probably achieve a similar effect by resizing the window.

> Providing some all-encompassing error type and actually returning it from run instead of doing the logging in there.
Important to note is that `run` cannot return, due to the nature of the web platform. On the web, your code isn't actually running in a loop but being called by browser APIs.

**Comment by vorner** [comment]
So, what happens if the inner application closure returns an error?

Nevertheless, on desktop I would like to be able to have some way to manually format the error or pop-up a message or something. Do you think there would be a way to achieve that while also adhering to restrictions of the web?

**Comment by vorner** [comment]
So, what happens if the inner application closure returns an error?

Nevertheless, on desktop I would like to be able to have some way to manually format the error or pop-up a message or something. Do you think there would be a way to achieve that while also adhering to restrictions of the web?

**Comment by ryanisaacg** [comment]
If you'd like to catch errors and handle them yourself, you can do that fairly easily:

```rust
pub async fn my_app_handler(...) {
    match my_app(...) {
        Ok(_) => { ... } // exited succesfully
        Err(e) => { ... } // exited with error, handle it here

**Comment by lenscas** [comment]
Also, the problem with multiple windows is: What is the web equivalent. With multiple windows at the same time you can only mimic that by spawning popup windows, which can only be done by interaction by the user, not to mention the fact that those generally leave a bad taste in the mouth of most users.

For switching windows out there are multiple things that can be done. 

- just clearing the canvas
- rendering a new canvas element
- rendering a whole new html layout
- doing any of the above, but also change the url to match the new state

From those, a combination of the last 2 sounds the most useful, however that also requires quicksilver to either add more configuration or dictate which html files should be used and when, along with the urls.

Add to this that these extra screens have been falling out of favor, with maybe an exception for engine specific launchers (And even they aren't really popular) and I think we can all agree that it is more effort than its worth.

**Comment by vorner** [comment]
OK, so I see the support for web is somewhat limiting the options and it's important target for the library.

So, are there things here that make sense from your point of view? An example with loading screen was mentioned. Does it also make sense to somehow tweak the error type, or make it generic, or do you prefer it staying as it is? Should I try sending a proposal as a PR?

**Comment by ryanisaacg** [comment]
> An example with loading screen was mentioned.

This is relatively lower-priority, though if you want to try at this feel free. 

> Does it also make sense to somehow tweak the error type, or make it generic, or do you prefer it staying as it is? Should I try sending a proposal as a PR?

Yes, please feel free to PR! If you can finagle the types so that returning `Result<(), QuicksilverError>` works with no ceremony that would be ideal. I would also take a new `run` method with a custom error type.

**Comment by ryanisaacg** [comment]
I think that we resolved everything here, so I'll close it.
