### ISSUE TITLE
Missing the example code

### ISSUE THREAD

**Issue by MarkuBu** [ryanisaacg/quicksilver#596]
Hi,
I'm missing the Rust example code from the web page like the camera example

https://ryanisaacg.com/quicksilver/example.html?camera

there is a link to the Rust source code, but the link is dead. There are only js files in the docs folder on Github

Are there any more advanced examples in Rust?

Greetings
Markus

**Comment by lenscas** [comment]
Right now quicksilver is getting a big overhaul, which is how the link got broken. I've linked the documentation and examples for both the 0.3 version and the 0.4-alpha version. 

Version 0.3
- [examples](https://github.com/ryanisaacg/quicksilver/tree/version-0.3/examples)
- [documentation](https://docs.rs/crate/quicksilver/0.3.20)

Version 0.4-alpha
- [examples](https://github.com/ryanisaacg/quicksilver/tree/master/examples)
- [documentation](https://docs.rs/crate/quicksilver/0.4.0-alpha0.3)

**Comment by ryanisaacg** [comment]
Thank you for pointing out the links are dead, I'll update them to point to the old examples for now.
