### ISSUE TITLE
Web text issue

### ISSUE THREAD

**Issue by IgneousRed** [ryanisaacg/quicksilver#598]
With the same code:
  on windows it works
  on web it only shows white background with no text

```rust
use quicksilver::{
  Future, Result,
  combinators::result,
  geom::{Shape, Vector},
  graphics::{Background::Img, Color, Font, FontStyle},
  lifecycle::{Asset, Settings, State, Window, run},
};

struct Main;

impl State for Main {
  fn new() -> Result<Self> {
    Ok(Self)
  }
  fn draw(&mut self, window: &mut Window) -> Result<()> {
    window.clear(Color::WHITE)?;
    Asset::new(Font::load("font.ttf")
      .and_then(|font| {
        let style = FontStyle::new(72.0, Color::BLACK);
        result(font.render("Text", &style))
      })).execute(|image| {
        window.draw(&image.area().with_center((400, 300)), Img(&image));
        Ok(())
      })
  }
}

fn main() {
  run::<Main>("Font Example", Vector::new(800, 600), Settings::default());
}
```
Unsure if I am doing something wrong... in making text content dynamic.

Environment: Windows 8.1, Firefox
Rust compiler version: Rust nightly 1.44.0
Quicksilver version: 0.3.22

**Comment by ryanisaacg** [comment]
Are there any errors in the developer console?

Also, I encourage you to try the current alpha releases if you're making use of text. The API is much improved.

**Comment by IgneousRed** [comment]
https://i.imgur.com/rgoMJLd.png Don't see any...
I did not had a great experience with the alpha... All the alpha examples (on alpha ver. ofc) kinda did not compile :$ If you want me I can file more issues. Was not sure if I missed some crucial part...

**Comment by lenscas** [comment]
I think Ryan was referring to browser console (press F12)

However, I think I see the problem. You are making the asset inside the draw method. Try to move the font loading and ideally the rendering to an image to the new method, because I'm pretty sure it just doesn't have enough time to load the font.

About the current state of the alpha: So far it always compiled for me, and it is much nicer to work with. So, personally I'm curious what you are running in to :)

**Comment by IgneousRed** [comment]
F12 does nothing for me :)

Even if I set draw_rate to 1000. / 1. It is still just white...
I am having difficulties separating font loading while still making it dynamic.

Anyway I will try to hop to Alpha again and we'll see
Also thank you both <3

**Comment by lenscas** [comment]
> F12 does nothing for me :)

which browser?



> Even if I set draw_rate to 1000. / 1. It is still just white...
> I am having difficulties separating font loading while still making it dynamic.

It isn't about the draw rate but probably just how browsers load stuff and how this interacts with the asset api. You can make it so only the font gets loaded in the new method and have the rest of the rendering happen in the draw method.

> Anyway I will try to hop to Alpha again and we'll see
I hope it works better for you now :)

**Comment by IgneousRed** [comment]
> which browser?
Environment: Windows 8.1, Firefox as stated before

> You can make it so only the font gets loaded in the new method and have the rest of the rendering happen in the draw method.
That is exactly what I am struggling with :D As some methods are no longer available

It is getting late...

**Comment by lenscas** [comment]
going from memory, something like this should work:
```rust
struct Main(Asset<Font>);

impl State for Main {
  fn new() -> Result<Self> {
    Ok(Self(Asset::new(Font::load("font.ttf"))
  }
  fn draw(&mut self, window: &mut Window) -> Result<()> {
    window.clear(Color::WHITE)?;
    self.execute(|image| {
        let style = FontStyle::new(72.0, Color::BLACK);
        let image = font.render("Text", &style);
        window.draw(&image.area().with_center((400, 300)), Img(&image));
        Ok(())
      })
  }
}
```

However, I remember this being able to leak memory when building for the web and I'm not sure if that got fixed. To fix that you also need to make it so you only render to the image whenever something changes.

**Comment by IgneousRed** [comment]
https://i.imgur.com/xAmzrhk.png No web console errors on the first code posted...

Your code after fixing two missing ")" ...
"no method named `execute` found for mutable reference `&mut Main` in the current scope
items from traits can only be used if the trait is implemented and in scope
the following traits define an item `execute`, perhaps you need to implement one of them:
candidate #1: `futures::future::Executor`
candidate #2: `futures::task_impl::std::Executor`"

**Comment by lenscas** [comment]
sorry, it was `self.0.execute`

**Comment by IgneousRed** [comment]
0. "no method named `area` found for enum `std::result::Result<quicksilver::graphics::image::Image, quicksilver::error::QuicksilverError>` in the current scope
method not found in `std::result::Result<quicksilver::graphics::image::Image, quicksilver::error::QuicksilverError>`"
1. "mismatched types
expected reference `&quicksilver::graphics::image::Image`
   found reference `&std::result::Result<quicksilver::graphics::image::Image, quicksilver::error::QuicksilverError>`"

**Comment by ryanisaacg** [comment]
I took a slightly closer look, and lenscas is definitely leading you down the right path. Your current code loads the asset every time you draw, which will never complete on web.

>  I did not had a great experience with the alpha... All the alpha examples (on alpha ver. ofc) kinda did not compile :$ If you want me I can file more issues. Was not sure if I missed some crucial part...

I would love bug reports for the alpha if you have them; that's how things will improve.

**Comment by lenscas** [comment]
seems like render returns a result rather than an image, however as execute wants a function that returns a result you can just use a `?` after calling render like so:` let image = font.render("Text", &style)?;`

just In the case that you are new to rust, you can read how error handling works here :
https://doc.rust-lang.org/edition-guide/rust-2018/error-handling-and-panics/the-question-mark-operator-for-easier-error-handling.html :)

**Comment by IgneousRed** [comment]
> I would love bug reports for the alpha if you have them; that's how things will improve.

It keep giving errors on run() and Settings as if they request non-alpha parameters. Few *window reloads* later, it works? Totally weird... Also it keeps messing up, so I tend to reload it every few h. Using both rls and analyzer.

> just In the case that you are new to rust

Not new, tho still fresh and was not toying with error handling much.
Will try to make it work...

**Comment by lenscas** [comment]
I think it is advised to only use rls OR rust-analyzer but not both.

Also, if you can share the project your experiencing these problems with it would be nice if you can share it. Then I can look if there is a problem with quicksilver or if something else is going wrong :)

**Comment by IgneousRed** [comment]
> I think it is advised to only use rls OR rust-analyzer but not both.

I meant "or" sry

> Also, if you can share the project your experiencing these problems with it would be nice if you can share it. Then I can look if there is a problem with quicksilver or if something else is going wrong :)

The thing I posted is basically the only content.
Also you meat a github repo?

**Comment by lenscas** [comment]
I do mean a github repo. why are you actually using nightly?

**Comment by IgneousRed** [comment]
I had to use it for a previous project.. I will set to stable and see If there are any difference in bad errors.. Also are you using discord? as this is straying to conversation and I wouldn't like to just spam the /issues...

**Comment by lenscas** [comment]
I quickly made a server https://discord.gg/J2GedH (Not sure how to easily DM someone you don't know )

**Comment by IgneousRed** [comment]
With the help of lenscas I get the problem... The asset is loading async while the .execute() does nothing if asset is loaded. As .execute() is called right after loading, it fails every time... tho it still works on win 8.1... interesting... Anyhow thank you both again!
I suppose I will just close the issue?

**Comment by ryanisaacg** [comment]
I'm glad you were able to solve the problem. Thanks @lenscas for helping out here!

I'll close this, but if you run into any other issues with 0.3.22 or the new alphas feel free to open new issues.
