### ISSUE TITLE
Unable to disable features

### ISSUE THREAD

**Issue by IgneousRed** [ryanisaacg/quicksilver#600]
Setting "default-features = false" causes multiple  "use of undeclared type or module `FontError`" errors to appear.
Even if no actual fonts are being used, the build error persists. 

Windows 8.1
Rust nightly 1.44.0
Quicksilver 0.4.0-alpha0.3

**Comment by ryanisaacg** [comment]
That's my bad! Should be a simple enough fix to put out in a patch release.

**Comment by vorner** [comment]
Hello

I've hit this too. I want to add that:

* No features → the above `FontError` problem.
* Enabling only the `"font"` feature → `no VectorFont in graphics::font` error (need to enable `"ttf"` too).
