### ISSUE TITLE
Empty page when started with cargo web start

### ISSUE THREAD

**Issue by vorner** [ryanisaacg/quicksilver#605]
**Describe the bug**

After some time of native testing, I've decided to try to run my game on the web too and tried to use `cargo web start` for it. I only get an empty page (I've tried to use multiple browsers). I've tried to run one of the examples in the quicksilver repository, to the same effect. I've tried both std-web and websys features (each one separately).

The debug console contains this:

```
TypeError: import object field '__wbindgen_placeholder__' is not an Object
```

I'm not sure if this is problem with quicksilver or with cargo web or where. I'm not experienced in any web development, I have only rough ideas how these things work so I don't know how to debug this. I hoped this would „just work“.

**To Reproduce**

1. `cargo web start --example 01_square --features web-sys` inside quicksilver repo.
2. Open `http://[::1]:8000`.
3. See an empty page load.

**Environment and versions (please complete the following information):**
- Environment: Gentoo linux, firefox 75.0 & falkon 3.1.0, cargo web 0.6.26
- Rust compiler version: rustc 1.44.0-nightly (b2e36e6c2 2020-04-22)
- Quicksilver verison: 0.4.0-alpha0.3 & current master

**Comment by lenscas** [comment]
the problem is that you enable the wrong feature.
use feature stdweb when using cargo web
and feature web-sys when using wasm-bindgen/web-sys.

Short explanation:
There are 2 main ways to get rust + JS to work together, stdweb and wasm-bindgen. They are incompatible with each other and both have made a project to automate some of the boring stuff.

For stdweb this project is`cargo web` and for wasm-bindgen it is `web-sys`.

**Comment by vorner** [comment]
Thanks for the hint. Indeed the example work with stdweb/cargo web. I still get empty page with my game, which let me to think it is general problem (it turns out that one panics before doing anything, but that's a separate problem and possibly mine).

To avoid the confusion, do you think it makes sense to extend the `Deploying for the web` section in the readme to mention the right feature? Should I send a pull request?

**Comment by lenscas** [comment]
I think it already does?
```
If you want to test your application locally, use cargo web start --features stdweb and open your favorite browser to the port it provides.
```
However, if you can make it more clear then I would say go for it. I'm pretty sure Ryan would approve it :)

I also believe there is a way to detect if cargo web is being used at compile time. If the same exist for wasm-bindgen then it might be an idea to throw an compile error if the wrong feature is enabled?

**Comment by vorner** [comment]
Ah, sorry, because of the alpha versions, `crates.io/crates/quicksilver` shows an outdated README :-(. Sorry for taking your time by me being blind/not looking at the right places.
