### ISSUE TITLE
An easy way to get the cursor location that takes into account resize strategy

### ISSUE THREAD

**Issue by lenscas** [ryanisaacg/quicksilver#620]
**Describe the problem you want to solve**
Now that quicksilver has resizes strategies I decided to try to implement it for my game. Drawing everything is no problem, however detecting where the mouse of the user is is currently problematic for me.

The problem I have is that calling `PointerMovedEvent::location()` gives me the position of the cursor in the screen without taking into account the current resize strategy. 

**Describe the solution you'd like**
Ideally, I would like `PointerMovedEvent::location()` to take into account the current resize strategy. 
Alternatively, a method in `ResizeHandler` that is able to take screen coordinates and calculate them with taking the resize strategy into account would also be good.

**Are you interested in contributing?**
I don't mind opening a pull request, however I'm not sure how to do this calculation.

**Comment by ryanisaacg** [comment]
Thank you for pointing that out! If I have the math correct in my head, it may be as simple as:

- Take the inverse of the Transform you get from the ResizeStrategy
- Apply it to the mouse position

I'm not 100% sure that will work, but I think it might.

**Comment by lenscas** [comment]
If you mean like
```rust
let projection = Transform::orthographic(screen);
while let Some(e) = wrapper.events.next_event().await {
    if let PointerMoved(e) = &e {
        wrapper.cursor_at = projection.inverse() * e.location();
    }
}
```
Then, I don't think it works. If I have the window be pretty much as big as my screen (screen-task bar) and have the cursor near the top left of the window, I get values like
```rust
[src/main.rs:45] self.cursor_at = Vector {
    x: 245936.44,
    y: -93894.91,
}
[src/main.rs:45] self.cursor_at = Vector {
    x: 45600.754,
    y: -109598.81,
}
```
If I don't resize the window, I get pretty much the same wrong values
```
[src/main.rs:45] self.cursor_at = Vector {
    x: 41981.832,
    y: -4507.5703,
}
[src/main.rs:45] self.cursor_at = Vector {
    x: 7169.051,
    y: -6101.6367,
}
```

In case my configuration is messing things up
```rust
const SIZE: Vector = Vector { x: 1366., y: 768. };
let resize_handler = ResizeHandler::Fit {
    aspect_width: 16.0,
    aspect_height: 9.0,
};
```

**Comment by ryanisaacg** [comment]
Oh you're right, I forgot that the viewport size and window size don't necessarily match. Well, that might require a bit more math then. When I get the chance I'll take a crack at this.

**Comment by lenscas** [comment]
I'm looking forward to it.
