### ISSUE TITLE
Are subimages still a thing? 

### ISSUE THREAD

**Issue by TheEmeraldFalcon** [ryanisaacg/quicksilver#629]
I currently can't find a way to make subimages, and I was wondering whether they've been removed, or whatelse.

**Comment by ryanisaacg** [comment]
You can't make an `Image` instance that is a subimage, but you can still draw subimages: https://docs.rs/quicksilver/0.4.0-alpha0.5/quicksilver/graphics/struct.Graphics.html#method.draw_subimage

**Comment by TheEmeraldFalcon** [comment]
ahh, okay, thanks!

**Comment by ryanisaacg** [comment]
No problem!
