### ISSUE TITLE
Rendering to surfaces also renders to regular window?

### ISSUE THREAD

**Issue by jgarvin** [ryanisaacg/quicksilver#630]
**Describe the bug**
Sorry ahead of time if this is intended behavior. My expectation would be that if I render to a `Surface` that I'm rendering to some offscreen buffer that should never appear on the visible screen unless I explicitly copy it there with `gfx.draw_image`. However this does not appear to be the case at least not with `stdweb`. The test program below draws a rectangle to a surface, but never tries to draw it on the screen. It shows up on the screen anyway.

**To Reproduce**
```
#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_mut)]

 use quicksilver::{
    geom::{Circle, Rectangle, Vector},
    graphics::{Color, Image, PixelFormat, Surface},
    run, Graphics, Input, Result, Settings, Window,
};

fn main() {
    run(
        Settings {
            title: "Square Example",
            ..Settings::default()
        },
        app,
    );
}

async fn app(window: Window, mut gfx: Graphics, mut input: Input) -> Result<()> {
    gfx.clear(Color::WHITE);
    // Create a surface, which allows rendering to an image
    let mut surface = Surface::new(
        &gfx,
        Image::from_raw(&gfx, None, 512, 512, PixelFormat::RGBA)?,
    )?;
    // Set the render area to the surface size
    gfx.fit_to_surface(&surface)?;
    gfx.fill_rect(
        &Rectangle::new(Vector::new(350.0, 100.0), Vector::new(100.0, 100.0)),
        Color::RED,
    );

    gfx.fit_to_window(&window);

    gfx.present(&window)?;
    loop {
        while let Some(_) = input.next_event().await {}
    }
}
```

**Environment and versions (please complete the following information):**
Environment: Ubuntu 19.10, Chrome Version 81.0.4044.138 (Official Build) (64-bit)
Rust compiler version: rustc 1.44.0 (49cae5576 2020-06-01)
Quicksilver verison: quicksilver = "0.4.0-alpha0.5"

**Comment by ryanisaacg** [comment]
`fit_to_window` and `fit_to_surface` don't set the render target, they set the size of the viewport. You want to `flush` to the `Surface` when you're done rendering to it.

This is probably not the most intuitive API, and you're not the first person to bang your shin on it. I'll throw reworking it on the alpha roadmap!

**Comment by jgarvin** [comment]
as long as it's intended for now I'll close :)
