### ISSUE TITLE
event loop iterates slowly

### ISSUE THREAD

**Issue by jgarvin** [ryanisaacg/quicksilver#632]
**Describe the bug**
The loop as provided in the examples seems to run very slowly. I am "animating" by moving some objects up 50 pixels every event loop iteration. If the loop were running at 30fps I would expect everything to be flying by in a blur, but instead it seems re-rendering is only happening about once per second, you can watch it.

I'm not totally familiar with the semantics of await yet, but I would expect that either you are periodically returning some sort of No-op event to keep things rendering, or that it should block until an input event happens. If the former, that event seems to be too infrequent for continuous rendering, if the latter, then something seems broken because I'm not giving any input and it's animating anyway.

**To Reproduce**
```
#![deny(unused_must_use)] // otherwise can ignore errors from void functions
#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use quicksilver::{
    geom::{Circle, Rectangle, Vector},
    graphics::{Color, FontRenderer, Image, PixelFormat, Surface, VectorFont},
    run, Graphics, Input, Result, Settings, Window,
};

fn main() {
    run(
        Settings {
            size: Vector::new(1920.0, 1080.0),
            title: "Square Example",
            ..Settings::default()
        },
        app,
    );
}

struct RenderTools<'a> {
    gfx: &'a mut Graphics,
    font: &'a mut FontRenderer,
}

struct TextChunk {
    position: Vector,
    size: Vector,
    text: String,
}

impl TextChunk {
    fn new(text: String) -> TextChunk {
        return TextChunk {
            position: Vector::new(0.0, 0.0),
            size: Vector::new(0.0, 0.0),
            text: text,
        };
    }

    fn render(&self, render_tools: &mut RenderTools) -> Result<()> {
        render_tools
            .font
            .draw(render_tools.gfx, &*self.text, Color::BLACK, self.position)?;
        Ok(())
    }
}

#[derive(Default)]
struct TextWindow {
    position: Vector,    
    history: Vec<TextChunk>,
}

impl TextWindow {
    fn render(&self, render_tools: &mut RenderTools) -> Result<()> {
        for chunk in &self.history {
            chunk.render(render_tools)?;
        }
        Ok(())
    }

    fn append(&mut self, mut chunk: TextChunk) -> () {
        for old_chunk in &mut self.history {
            old_chunk.position.y -= 50.0;
        }
        if self.history.len() >= 100 {
            self.history.remove(0);
        }
        chunk.position.y += 500.0;
        self.history.push(chunk);
    }
}

async fn app(window: Window, mut gfx: Graphics, mut input: Input) -> Result<()> {
    // Clear the screen to a blank, white color
    gfx.clear(Color::WHITE);
    // Paint a blue square with a red outline in the center of our screen
    // It should have a top-left of (350, 100) and a size of (150, 100)
    let rect = Rectangle::new(Vector::new(350.0, 100.0), Vector::new(100.0, 100.0));
    let ttf = VectorFont::load("font.ttf").await?;

    let mut font = ttf.to_renderer(&gfx, 72.0)?;
    gfx.fit_to_window(&window);

    let mut render_tools = RenderTools {
        gfx: &mut gfx,
        font: &mut font,
    };
    let mut text_window = TextWindow::default();
    let mut i: u32 = 0;
    loop {
        while let Some(_) = input.next_event().await {}
        render_tools.gfx.clear(Color::WHITE);
        text_window.render(&mut render_tools)?;
        i += 1;
        if i % 10 == 0 {
            let chunk = TextChunk::new(format!("hello {}", i));
            text_window.append(chunk);
        }
        render_tools.gfx.present(&window)?;
    }
}

```

**Environment and versions (please complete the following information):**
Environment: Ubuntu 19.10, Chrome Version 81.0.4044.138 (Official Build) (64-bit)
Rust compiler version: rustc 1.44.0 (49cae5576 2020-06-01)
Quicksilver verison: quicksilver = "0.4.0-alpha0.5"

**Comment by lenscas** [comment]
> The loop as provided in the examples seems to run very slowly. I am "animating" by moving some objects up 50 pixels every event loop iteration

That doesn't seem to be exactly what the code does, as it contains an if to only add a new piece of text every 10th iteration, rather than every iteration.
```rust
        i += 1;
        if i % 10 == 0 {
            let chunk = TextChunk::new(format!("hello {}", i));
            text_window.append(chunk);
        }
```
I think this is the cause for the rendering looking slow because even at 60 iterations per second you only get a new piece of text 6 times per second.

**Comment by jgarvin** [comment]
Sorry should have mentioned that. It looked like it was only updating once per second or slower. Earlier I did another test where I just moved text one pixel every iteration, which I'd expect to definitely fly across the screen, and it also noticably crawled. I can upload that simpler example tomorrow.

**Comment by lenscas** [comment]
I tried running the code you gave. In its current form it seemed to work fine for me (haven't counted the frames but it felt like 6fps) and I also ran it without the if and that also seemed fine (again, didn't count fps).

**Comment by jgarvin** [comment]
Sorry for the noise, I think this one was my mistake, figured it out trying to make a more minimal case.
