### ISSUE TITLE
How to get release key event

### ISSUE THREAD

**Issue by malynome** [ryanisaacg/quicksilver#634]
Is there an easy way to get the state of a keyboard input event, other than when it is pressed? 
Sorry if I'm just being blind, but I can't seem to find an easy way to check if a key has been released.
Thanks in advance!
~Malynome

**Comment by lenscas** [comment]
when listening to events, you get https://docs.rs/quicksilver/0.4.0-alpha0.5/quicksilver/input/enum.Event.html whenever an event fires.

You get `PointerInput(PointerInputEvent),` every time the state of a button changed. PointerInputEvent is https://docs.rs/quicksilver/0.4.0-alpha0.5/quicksilver/input/struct.PointerInputEvent.html

So, simply use its `is_down` method to see if it is down or not
