### ISSUE TITLE
Derive Debug/Clone for Timer

### ISSUE THREAD

**Issue by MinusGix** [ryanisaacg/quicksilver#645]
Currently you can not clone a `Timer` instance, print it as Debug, or check for equality.

It would be nice to have Debug, Clone, and perhaps Copy / Eq / PartialEq implemented.

I'd be fine with implementing this myself (though it's a rather small change), and that is what I was going to do, but I wasn't entirely sure what I would add to `CHANGES.md`. Do you add a new version, ex `v0.4.0-alpha0.7` (and then you have to change everywhere else..) to hold the change mention, or simply append it to the current `v0.4.0-alpha0.6` list? If this is a semver pattern, I'm not quite used to that.

**Comment by lenscas** [comment]
generally there is a 
```
## WIP
```
header above all the other version. This would be where you put your changes under and it is then up to ryan to move them to the new version when he made one. It seems that the last version update accidentally got rid of this header. Just add it back if you make an PR.

I am not sure what Eq/PartialEq would do on timers though? Would it compare their tick speed? As for Copy, I'm neutral on it.

**Comment by MinusGix** [comment]
Ah, yeah, Eq/PartialEq doesn't make complete sense on Timer. I'll try making a PR for it with Debug + Clone.
